package com.gome.gmhx.entity;

public class HxUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_user_role.user_id
     *
     * @mbggenerated Mon Jul 14 17:18:57 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_user_role.role_id
     *
     * @mbggenerated Mon Jul 14 17:18:57 CST 2014
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_user_role.user_id
     *
     * @return the value of hx_user_role.user_id
     *
     * @mbggenerated Mon Jul 14 17:18:57 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_user_role.user_id
     *
     * @param userId the value for hx_user_role.user_id
     *
     * @mbggenerated Mon Jul 14 17:18:57 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_user_role.role_id
     *
     * @return the value of hx_user_role.role_id
     *
     * @mbggenerated Mon Jul 14 17:18:57 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_user_role.role_id
     *
     * @param roleId the value for hx_user_role.role_id
     *
     * @mbggenerated Mon Jul 14 17:18:57 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_user_role
     *
     * @mbggenerated Mon Jul 14 17:18:57 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append("]");
        return sb.toString();
    }
}