package com.gome.gmhx.dao.basicdata;


import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.gome.common.page.Page;
import com.gome.gmhx.entity.HxGoodbill;
import com.gome.gmhx.entity.HxGoodbillExample;
import com.gome.gmhx.entity.HxGoodbillKey;

@Repository("hxGoodbillDao")
public interface HxGoodbillDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int countByExample(HxGoodbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int deleteByExample(HxGoodbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int deleteByPrimaryKey(HxGoodbillKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int insert(HxGoodbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int insertSelective(HxGoodbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    List<HxGoodbill> selectByExample(HxGoodbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    HxGoodbill selectByPrimaryKey(HxGoodbillKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") HxGoodbill record, @Param("example") HxGoodbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int updateByExample(@Param("record") HxGoodbill record, @Param("example") HxGoodbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int updateByPrimaryKeySelective(HxGoodbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    int updateByPrimaryKey(HxGoodbill record);

	List<Map<String, Object>> getHxGoodbillPageList(Page page);

	List<Map<String, Object>>  getBillNumExport(HxGoodbill bill);
	
	void insertGoodbillBatch(List<Object> list);
	
}