package com.gome.gmhx.entity;

import java.math.BigDecimal;

public class JlRepairMeasures {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_repair_measures.WXD01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    private BigDecimal wxd01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_repair_measures.GSXX01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    private String gsxx01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_repair_measures.WXCS01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    private String wxcs01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_repair_measures.WXCSMC
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    private String wxcsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_repair_measures.WXCSFY
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    private BigDecimal wxcsfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_repair_measures.SL
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    private BigDecimal sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_repair_measures.WXCSCB
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    private BigDecimal wxcscb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_repair_measures.WXD01
     *
     * @return the value of jl_repair_measures.WXD01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public BigDecimal getWxd01() {
        return wxd01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_repair_measures.WXD01
     *
     * @param wxd01 the value for jl_repair_measures.WXD01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public void setWxd01(BigDecimal wxd01) {
        this.wxd01 = wxd01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_repair_measures.GSXX01
     *
     * @return the value of jl_repair_measures.GSXX01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public String getGsxx01() {
        return gsxx01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_repair_measures.GSXX01
     *
     * @param gsxx01 the value for jl_repair_measures.GSXX01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public void setGsxx01(String gsxx01) {
        this.gsxx01 = gsxx01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_repair_measures.WXCS01
     *
     * @return the value of jl_repair_measures.WXCS01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public String getWxcs01() {
        return wxcs01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_repair_measures.WXCS01
     *
     * @param wxcs01 the value for jl_repair_measures.WXCS01
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public void setWxcs01(String wxcs01) {
        this.wxcs01 = wxcs01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_repair_measures.WXCSMC
     *
     * @return the value of jl_repair_measures.WXCSMC
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public String getWxcsmc() {
        return wxcsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_repair_measures.WXCSMC
     *
     * @param wxcsmc the value for jl_repair_measures.WXCSMC
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public void setWxcsmc(String wxcsmc) {
        this.wxcsmc = wxcsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_repair_measures.WXCSFY
     *
     * @return the value of jl_repair_measures.WXCSFY
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public BigDecimal getWxcsfy() {
        return wxcsfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_repair_measures.WXCSFY
     *
     * @param wxcsfy the value for jl_repair_measures.WXCSFY
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public void setWxcsfy(BigDecimal wxcsfy) {
        this.wxcsfy = wxcsfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_repair_measures.SL
     *
     * @return the value of jl_repair_measures.SL
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public BigDecimal getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_repair_measures.SL
     *
     * @param sl the value for jl_repair_measures.SL
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public void setSl(BigDecimal sl) {
        this.sl = sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_repair_measures.WXCSCB
     *
     * @return the value of jl_repair_measures.WXCSCB
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public BigDecimal getWxcscb() {
        return wxcscb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_repair_measures.WXCSCB
     *
     * @param wxcscb the value for jl_repair_measures.WXCSCB
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    public void setWxcscb(BigDecimal wxcscb) {
        this.wxcscb = wxcscb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_repair_measures
     *
     * @mbggenerated Thu Nov 13 17:24:32 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wxd01=").append(wxd01);
        sb.append(", gsxx01=").append(gsxx01);
        sb.append(", wxcs01=").append(wxcs01);
        sb.append(", wxcsmc=").append(wxcsmc);
        sb.append(", wxcsfy=").append(wxcsfy);
        sb.append(", sl=").append(sl);
        sb.append(", wxcscb=").append(wxcscb);
        sb.append("]");
        return sb.toString();
    }
}