package com.gome.gmhx.entity;

public class EccGoodsCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_goods_category.CLASS
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    private String class_;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_goods_category.KSCHL
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    private String kschl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_goods_category.ZFLJB
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    private String zfljb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_goods_category.ZSJFLDM
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    private String zsjfldm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_goods_category.ZSFMJ
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    private String zsfmj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_goods_category.ABTNR
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    private String abtnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_goods_category.VTEXT
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    private String vtext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_goods_category.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    private String updateFlag;

	public String getClass_() {
		return class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_goods_category.KSCHL
     *
     * @return the value of ecc_goods_category.KSCHL
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public String getKschl() {
        return kschl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_goods_category.KSCHL
     *
     * @param kschl the value for ecc_goods_category.KSCHL
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public void setKschl(String kschl) {
        this.kschl = kschl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_goods_category.ZFLJB
     *
     * @return the value of ecc_goods_category.ZFLJB
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public String getZfljb() {
        return zfljb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_goods_category.ZFLJB
     *
     * @param zfljb the value for ecc_goods_category.ZFLJB
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public void setZfljb(String zfljb) {
        this.zfljb = zfljb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_goods_category.ZSJFLDM
     *
     * @return the value of ecc_goods_category.ZSJFLDM
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public String getZsjfldm() {
        return zsjfldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_goods_category.ZSJFLDM
     *
     * @param zsjfldm the value for ecc_goods_category.ZSJFLDM
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public void setZsjfldm(String zsjfldm) {
        this.zsjfldm = zsjfldm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_goods_category.ZSFMJ
     *
     * @return the value of ecc_goods_category.ZSFMJ
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public String getZsfmj() {
        return zsfmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_goods_category.ZSFMJ
     *
     * @param zsfmj the value for ecc_goods_category.ZSFMJ
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public void setZsfmj(String zsfmj) {
        this.zsfmj = zsfmj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_goods_category.ABTNR
     *
     * @return the value of ecc_goods_category.ABTNR
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public String getAbtnr() {
        return abtnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_goods_category.ABTNR
     *
     * @param abtnr the value for ecc_goods_category.ABTNR
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public void setAbtnr(String abtnr) {
        this.abtnr = abtnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_goods_category.VTEXT
     *
     * @return the value of ecc_goods_category.VTEXT
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public String getVtext() {
        return vtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_goods_category.VTEXT
     *
     * @param vtext the value for ecc_goods_category.VTEXT
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public void setVtext(String vtext) {
        this.vtext = vtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_goods_category.UPDATE_FLAG
     *
     * @return the value of ecc_goods_category.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_goods_category.UPDATE_FLAG
     *
     * @param updateFlag the value for ecc_goods_category.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:24:57 CST 2014
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }
}