package com.gome.gmhx.entity;

import java.util.Date;

public class HxFittingLocation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.fitting_id
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private Integer fittingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.organization_name
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private String organizationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.material_type
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private String materialType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.fittings_code
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private String fittingsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.fittings_name
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private String fittingsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.location
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.note
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.create_date
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_fitting_location.modifie_date
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    private Date modifieDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.fitting_id
     *
     * @return the value of hx_fitting_location.fitting_id
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public Integer getFittingId() {
        return fittingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.fitting_id
     *
     * @param fittingId the value for hx_fitting_location.fitting_id
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setFittingId(Integer fittingId) {
        this.fittingId = fittingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.organization_name
     *
     * @return the value of hx_fitting_location.organization_name
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.organization_name
     *
     * @param organizationName the value for hx_fitting_location.organization_name
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.material_type
     *
     * @return the value of hx_fitting_location.material_type
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public String getMaterialType() {
        return materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.material_type
     *
     * @param materialType the value for hx_fitting_location.material_type
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setMaterialType(String materialType) {
        this.materialType = materialType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.fittings_code
     *
     * @return the value of hx_fitting_location.fittings_code
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public String getFittingsCode() {
        return fittingsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.fittings_code
     *
     * @param fittingsCode the value for hx_fitting_location.fittings_code
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setFittingsCode(String fittingsCode) {
        this.fittingsCode = fittingsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.fittings_name
     *
     * @return the value of hx_fitting_location.fittings_name
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public String getFittingsName() {
        return fittingsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.fittings_name
     *
     * @param fittingsName the value for hx_fitting_location.fittings_name
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setFittingsName(String fittingsName) {
        this.fittingsName = fittingsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.location
     *
     * @return the value of hx_fitting_location.location
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.location
     *
     * @param location the value for hx_fitting_location.location
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.note
     *
     * @return the value of hx_fitting_location.note
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.note
     *
     * @param note the value for hx_fitting_location.note
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.create_date
     *
     * @return the value of hx_fitting_location.create_date
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.create_date
     *
     * @param createDate the value for hx_fitting_location.create_date
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_fitting_location.modifie_date
     *
     * @return the value of hx_fitting_location.modifie_date
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public Date getModifieDate() {
        return modifieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_fitting_location.modifie_date
     *
     * @param modifieDate the value for hx_fitting_location.modifie_date
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    public void setModifieDate(Date modifieDate) {
        this.modifieDate = modifieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_fitting_location
     *
     * @mbggenerated Mon Aug 18 11:37:13 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fittingId=").append(fittingId);
        sb.append(", organizationName=").append(organizationName);
        sb.append(", materialType=").append(materialType);
        sb.append(", fittingsCode=").append(fittingsCode);
        sb.append(", fittingsName=").append(fittingsName);
        sb.append(", location=").append(location);
        sb.append(", note=").append(note);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifieDate=").append(modifieDate);
        sb.append("]");
        return sb.toString();
    }
    
    public HxFittingLocation(){
    	this.createDate=new Date();
    	this.modifieDate=new Date();
    }
}