package com.gome.gmhx.entity;

public class EccStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.VKORG
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String vkorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.WERKS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String werks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.BUKRS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String bukrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.NAME1
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String name1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.ZVKGRP
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String zvkgrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.ZBEZEI
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String zbezei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.ZVKBUR
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String zvkbur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.ZBEZEI2
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String zbezei2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.STRAS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String stras;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.TELF1
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String telf1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_store.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    private String updateFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.VKORG
     *
     * @return the value of ecc_store.VKORG
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getVkorg() {
        return vkorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.VKORG
     *
     * @param vkorg the value for ecc_store.VKORG
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setVkorg(String vkorg) {
        this.vkorg = vkorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.WERKS
     *
     * @return the value of ecc_store.WERKS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getWerks() {
        return werks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.WERKS
     *
     * @param werks the value for ecc_store.WERKS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setWerks(String werks) {
        this.werks = werks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.BUKRS
     *
     * @return the value of ecc_store.BUKRS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getBukrs() {
        return bukrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.BUKRS
     *
     * @param bukrs the value for ecc_store.BUKRS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setBukrs(String bukrs) {
        this.bukrs = bukrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.NAME1
     *
     * @return the value of ecc_store.NAME1
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.NAME1
     *
     * @param name1 the value for ecc_store.NAME1
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setName1(String name1) {
        this.name1 = name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.ZVKGRP
     *
     * @return the value of ecc_store.ZVKGRP
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getZvkgrp() {
        return zvkgrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.ZVKGRP
     *
     * @param zvkgrp the value for ecc_store.ZVKGRP
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setZvkgrp(String zvkgrp) {
        this.zvkgrp = zvkgrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.ZBEZEI
     *
     * @return the value of ecc_store.ZBEZEI
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getZbezei() {
        return zbezei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.ZBEZEI
     *
     * @param zbezei the value for ecc_store.ZBEZEI
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setZbezei(String zbezei) {
        this.zbezei = zbezei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.ZVKBUR
     *
     * @return the value of ecc_store.ZVKBUR
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getZvkbur() {
        return zvkbur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.ZVKBUR
     *
     * @param zvkbur the value for ecc_store.ZVKBUR
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setZvkbur(String zvkbur) {
        this.zvkbur = zvkbur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.ZBEZEI2
     *
     * @return the value of ecc_store.ZBEZEI2
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getZbezei2() {
        return zbezei2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.ZBEZEI2
     *
     * @param zbezei2 the value for ecc_store.ZBEZEI2
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setZbezei2(String zbezei2) {
        this.zbezei2 = zbezei2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.STRAS
     *
     * @return the value of ecc_store.STRAS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getStras() {
        return stras;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.STRAS
     *
     * @param stras the value for ecc_store.STRAS
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setStras(String stras) {
        this.stras = stras;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.TELF1
     *
     * @return the value of ecc_store.TELF1
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getTelf1() {
        return telf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.TELF1
     *
     * @param telf1 the value for ecc_store.TELF1
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setTelf1(String telf1) {
        this.telf1 = telf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_store.UPDATE_FLAG
     *
     * @return the value of ecc_store.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_store.UPDATE_FLAG
     *
     * @param updateFlag the value for ecc_store.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecc_store
     *
     * @mbggenerated Thu Jul 31 09:31:18 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vkorg=").append(vkorg);
        sb.append(", werks=").append(werks);
        sb.append(", bukrs=").append(bukrs);
        sb.append(", name1=").append(name1);
        sb.append(", zvkgrp=").append(zvkgrp);
        sb.append(", zbezei=").append(zbezei);
        sb.append(", zvkbur=").append(zvkbur);
        sb.append(", zbezei2=").append(zbezei2);
        sb.append(", stras=").append(stras);
        sb.append(", telf1=").append(telf1);
        sb.append(", updateFlag=").append(updateFlag);
        sb.append("]");
        return sb.toString();
    }
}