<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/jquery-1.8.1.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/jquery.validate.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/messages_cn.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-easyui-1.3.6/jquery.easyui.min.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery-easyui-1.3.6/locale/easyui-lang-zh_CN.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/validate.js"></script>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/extEasyUI.js"></script>
<link rel="stylesheet" href="<%=request.getContextPath()%>/js/jquery-easyui-1.3.6/themes/default/easyui.css" type="text/css"/>
<link rel="stylesheet" href="<%=request.getContextPath()%>/js/jquery-easyui-1.3.6/themes/icon.css" type="text/css"/>
<script type="text/javascript" src="<%=request.getContextPath()%>/js/jquery/extend_validate.js"></script>