package com.gome.gmhx.dao.workflow;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.gome.common.page.Page;
import com.gome.gmhx.jbpm.JbpmTaskTrajectory;

@Repository("jbpmTaskTrajectoryDao")
public interface JbpmTaskTrajectoryDao{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_TASK_TRAJECTTORY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_TASK_TRAJECTTORY
     *
     * @mbggenerated
     */
    int insert(JbpmTaskTrajectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_TASK_TRAJECTTORY
     *
     * @mbggenerated
     */
    int insertSelective(JbpmTaskTrajectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_TASK_TRAJECTTORY
     *
     * @mbggenerated
     */
    JbpmTaskTrajectory selectByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_TASK_TRAJECTTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JbpmTaskTrajectory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JBPM4_TASK_TRAJECTTORY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JbpmTaskTrajectory record);

    List<Map<String, Object>>  getWorkPageList(Page page);

	List<Map<String, Object>> getTaskTrajeCttoryPageList(Page page);

	String processInstanceIdToVal(String processInstanceId);

	List<Map<String, Object>> getWorkMonitoringPageList(Page page);
}