package com.gome.gmhx.entity;

public class EccRegional {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_regional.BZIRK
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    private String bzirk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_regional.BZTXT
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    private String bztxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_regional.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    private String updateFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_regional.BZIRK
     *
     * @return the value of ecc_regional.BZIRK
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    public String getBzirk() {
        return bzirk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_regional.BZIRK
     *
     * @param bzirk the value for ecc_regional.BZIRK
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    public void setBzirk(String bzirk) {
        this.bzirk = bzirk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_regional.BZTXT
     *
     * @return the value of ecc_regional.BZTXT
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    public String getBztxt() {
        return bztxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_regional.BZTXT
     *
     * @param bztxt the value for ecc_regional.BZTXT
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    public void setBztxt(String bztxt) {
        this.bztxt = bztxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_regional.UPDATE_FLAG
     *
     * @return the value of ecc_regional.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_regional.UPDATE_FLAG
     *
     * @param updateFlag the value for ecc_regional.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecc_regional
     *
     * @mbggenerated Thu Jul 31 09:29:07 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bzirk=").append(bzirk);
        sb.append(", bztxt=").append(bztxt);
        sb.append(", updateFlag=").append(updateFlag);
        sb.append("]");
        return sb.toString();
    }
}