package com.gome.gmhx.entity;

public class HxMenu {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_menu.menu_id
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_menu.parent_id
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_menu.menu_name
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_menu.url
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_menu.icon_url
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_menu.sort
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_menu.menu_desc
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    private String menuDesc;
    
    private String parentName;
    
    private String isLeafNode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_menu.menu_id
     *
     * @return the value of hx_menu.menu_id
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_menu.menu_id
     *
     * @param menuId the value for hx_menu.menu_id
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_menu.parent_id
     *
     * @return the value of hx_menu.parent_id
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_menu.parent_id
     *
     * @param parentId the value for hx_menu.parent_id
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_menu.menu_name
     *
     * @return the value of hx_menu.menu_name
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_menu.menu_name
     *
     * @param menuName the value for hx_menu.menu_name
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_menu.url
     *
     * @return the value of hx_menu.url
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_menu.url
     *
     * @param url the value for hx_menu.url
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_menu.icon_url
     *
     * @return the value of hx_menu.icon_url
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_menu.icon_url
     *
     * @param iconUrl the value for hx_menu.icon_url
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_menu.sort
     *
     * @return the value of hx_menu.sort
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_menu.sort
     *
     * @param sort the value for hx_menu.sort
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_menu.menu_desc
     *
     * @return the value of hx_menu.menu_desc
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_menu.menu_desc
     *
     * @param menuDesc the value for hx_menu.menu_desc
     *
     * @mbggenerated Fri Jul 18 13:49:22 CST 2014
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getIsLeafNode() {
		return isLeafNode;
	}

	public void setIsLeafNode(String isLeafNode) {
		this.isLeafNode = isLeafNode;
	}
    
}
