package com.gome.gmhx.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.gome.gmhx.jbpm.JbpmWorkEntity;

public class HxServiceTicket implements JbpmWorkEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.jl_service_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String jlServiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.customer_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.product_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.sequence
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.category
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String category;
    
    private BigDecimal dataFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_type
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.link_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String linkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.link_phone
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String linkPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.appointment_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd")
    private Date appointmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.appointment_quantum
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String appointmentQuantum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.urgency_degree
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String urgencyDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.dispatch_info
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String dispatchInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.customer_describe
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String customerDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.inform_repair_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd")
    private Date informRepairDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.repair_mode
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String repairMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.move_mode
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String moveMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.charge_fluorine_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String chargeFluorineNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.distance_apply_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String distanceApplyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_pattern
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String servicePattern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_card_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String serviceCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String serviceMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd")
    private Date serviceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float trafficFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float delayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float otherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.product_exterior_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String productExteriorSatisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.product_exterior_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String productExteriorSignificance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.price_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String priceSatisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.price_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String priceSignificance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String serviceSatisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String serviceSignificance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.quality_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String qualitySatisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.quality_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String qualitySignificance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.physiology_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String physiologySatisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.physiology_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String physiologySignificance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.customer_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String customerSatisfaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.warranty_policy
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String warrantyPolicy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.is_replace_parts
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Integer isReplaceParts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.manul_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String manulNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.is_double_install
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String isDoubleInstall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.input_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date inputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.appointment_install_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd")
    private Date appointmentInstallDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.move_address
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String moveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.machine_check_fault_reason
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String machineCheckFaultReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.center_check_traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float centerCheckTrafficFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.center_check_delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float centerCheckDelayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.center_check_other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float centerCheckOtherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.center_check_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String centerCheckMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.center_check_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date centerCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.center_check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String centerCheckResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.center_check_comment
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String centerCheckComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.headquarters_check_traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float headquartersCheckTrafficFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.headquarters_check_delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float headquartersCheckDelayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.headquarters_check_other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Float headquartersCheckOtherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.headquarters_check_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String headquartersCheckMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.headquarters_check_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date headquartersCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.headquarters_check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String headquartersCheckResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.headquarters_check_comment
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String headquartersCheckComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String checkResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.recall_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String recallMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.recall_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String recallResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.recall_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date recallTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.is_clear
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Boolean isClear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_status
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String serviceStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.center
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String center;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.website
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.comment_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String commentS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.create_man_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String createManS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.create_organization_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String createOrganizationS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.create_time_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date createTimeS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.alter_man_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String alterManS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.alter_organization_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String alterOrganizationS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.alter_time_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date alterTimeS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.process_instance_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String processInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.applicant
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.apply_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.service_unit
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String serviceUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.create_position
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private String createPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_ticket.is_pass_check
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    private Boolean isPassCheck;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_id
     *
     * @return the value of hx_service_ticket.service_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_id
     *
     * @param serviceId the value for hx_service_ticket.service_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.jl_service_id
     *
     * @return the value of hx_service_ticket.jl_service_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getJlServiceId() {
        return jlServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.jl_service_id
     *
     * @param jlServiceId the value for hx_service_ticket.jl_service_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setJlServiceId(String jlServiceId) {
        this.jlServiceId = jlServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.customer_id
     *
     * @return the value of hx_service_ticket.customer_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.customer_id
     *
     * @param customerId the value for hx_service_ticket.customer_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.product_id
     *
     * @return the value of hx_service_ticket.product_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.product_id
     *
     * @param productId the value for hx_service_ticket.product_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.sequence
     *
     * @return the value of hx_service_ticket.sequence
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.sequence
     *
     * @param sequence the value for hx_service_ticket.sequence
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.category
     *
     * @return the value of hx_service_ticket.category
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.category
     *
     * @param category the value for hx_service_ticket.category
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_type
     *
     * @return the value of hx_service_ticket.service_type
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_type
     *
     * @param serviceType the value for hx_service_ticket.service_type
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.link_man
     *
     * @return the value of hx_service_ticket.link_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.link_man
     *
     * @param linkMan the value for hx_service_ticket.link_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.link_phone
     *
     * @return the value of hx_service_ticket.link_phone
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.link_phone
     *
     * @param linkPhone the value for hx_service_ticket.link_phone
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.appointment_date
     *
     * @return the value of hx_service_ticket.appointment_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getAppointmentDate() {
        return appointmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.appointment_date
     *
     * @param appointmentDate the value for hx_service_ticket.appointment_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setAppointmentDate(Date appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.appointment_quantum
     *
     * @return the value of hx_service_ticket.appointment_quantum
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getAppointmentQuantum() {
        return appointmentQuantum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.appointment_quantum
     *
     * @param appointmentQuantum the value for hx_service_ticket.appointment_quantum
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setAppointmentQuantum(String appointmentQuantum) {
        this.appointmentQuantum = appointmentQuantum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.urgency_degree
     *
     * @return the value of hx_service_ticket.urgency_degree
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getUrgencyDegree() {
        return urgencyDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.urgency_degree
     *
     * @param urgencyDegree the value for hx_service_ticket.urgency_degree
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setUrgencyDegree(String urgencyDegree) {
        this.urgencyDegree = urgencyDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.dispatch_info
     *
     * @return the value of hx_service_ticket.dispatch_info
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getDispatchInfo() {
        return dispatchInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.dispatch_info
     *
     * @param dispatchInfo the value for hx_service_ticket.dispatch_info
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setDispatchInfo(String dispatchInfo) {
        this.dispatchInfo = dispatchInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.customer_describe
     *
     * @return the value of hx_service_ticket.customer_describe
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCustomerDescribe() {
        return customerDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.customer_describe
     *
     * @param customerDescribe the value for hx_service_ticket.customer_describe
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCustomerDescribe(String customerDescribe) {
        this.customerDescribe = customerDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.inform_repair_date
     *
     * @return the value of hx_service_ticket.inform_repair_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getInformRepairDate() {
        return informRepairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.inform_repair_date
     *
     * @param informRepairDate the value for hx_service_ticket.inform_repair_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setInformRepairDate(Date informRepairDate) {
        this.informRepairDate = informRepairDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.repair_mode
     *
     * @return the value of hx_service_ticket.repair_mode
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getRepairMode() {
        return repairMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.repair_mode
     *
     * @param repairMode the value for hx_service_ticket.repair_mode
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setRepairMode(String repairMode) {
        this.repairMode = repairMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.move_mode
     *
     * @return the value of hx_service_ticket.move_mode
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getMoveMode() {
        return moveMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.move_mode
     *
     * @param moveMode the value for hx_service_ticket.move_mode
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setMoveMode(String moveMode) {
        this.moveMode = moveMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.charge_fluorine_num
     *
     * @return the value of hx_service_ticket.charge_fluorine_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getChargeFluorineNum() {
        return chargeFluorineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.charge_fluorine_num
     *
     * @param chargeFluorineNum the value for hx_service_ticket.charge_fluorine_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setChargeFluorineNum(String chargeFluorineNum) {
        this.chargeFluorineNum = chargeFluorineNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.distance_apply_num
     *
     * @return the value of hx_service_ticket.distance_apply_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getDistanceApplyNum() {
        return distanceApplyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.distance_apply_num
     *
     * @param distanceApplyNum the value for hx_service_ticket.distance_apply_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setDistanceApplyNum(String distanceApplyNum) {
        this.distanceApplyNum = distanceApplyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_pattern
     *
     * @return the value of hx_service_ticket.service_pattern
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServicePattern() {
        return servicePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_pattern
     *
     * @param servicePattern the value for hx_service_ticket.service_pattern
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServicePattern(String servicePattern) {
        this.servicePattern = servicePattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_card_num
     *
     * @return the value of hx_service_ticket.service_card_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServiceCardNum() {
        return serviceCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_card_num
     *
     * @param serviceCardNum the value for hx_service_ticket.service_card_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceCardNum(String serviceCardNum) {
        this.serviceCardNum = serviceCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_man
     *
     * @return the value of hx_service_ticket.service_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServiceMan() {
        return serviceMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_man
     *
     * @param serviceMan the value for hx_service_ticket.service_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceMan(String serviceMan) {
        this.serviceMan = serviceMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_date
     *
     * @return the value of hx_service_ticket.service_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getServiceDate() {
        return serviceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_date
     *
     * @param serviceDate the value for hx_service_ticket.service_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceDate(Date serviceDate) {
        this.serviceDate = serviceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.traffic_fee
     *
     * @return the value of hx_service_ticket.traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getTrafficFee() {
        return trafficFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.traffic_fee
     *
     * @param trafficFee the value for hx_service_ticket.traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setTrafficFee(Float trafficFee) {
        this.trafficFee = trafficFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.delay_fee
     *
     * @return the value of hx_service_ticket.delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getDelayFee() {
        return delayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.delay_fee
     *
     * @param delayFee the value for hx_service_ticket.delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setDelayFee(Float delayFee) {
        this.delayFee = delayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.other_fee
     *
     * @return the value of hx_service_ticket.other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getOtherFee() {
        return otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.other_fee
     *
     * @param otherFee the value for hx_service_ticket.other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setOtherFee(Float otherFee) {
        this.otherFee = otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.product_exterior_satisfaction
     *
     * @return the value of hx_service_ticket.product_exterior_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getProductExteriorSatisfaction() {
        return productExteriorSatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.product_exterior_satisfaction
     *
     * @param productExteriorSatisfaction the value for hx_service_ticket.product_exterior_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setProductExteriorSatisfaction(String productExteriorSatisfaction) {
        this.productExteriorSatisfaction = productExteriorSatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.product_exterior_significance
     *
     * @return the value of hx_service_ticket.product_exterior_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getProductExteriorSignificance() {
        return productExteriorSignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.product_exterior_significance
     *
     * @param productExteriorSignificance the value for hx_service_ticket.product_exterior_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setProductExteriorSignificance(String productExteriorSignificance) {
        this.productExteriorSignificance = productExteriorSignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.price_satisfaction
     *
     * @return the value of hx_service_ticket.price_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getPriceSatisfaction() {
        return priceSatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.price_satisfaction
     *
     * @param priceSatisfaction the value for hx_service_ticket.price_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setPriceSatisfaction(String priceSatisfaction) {
        this.priceSatisfaction = priceSatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.price_significance
     *
     * @return the value of hx_service_ticket.price_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getPriceSignificance() {
        return priceSignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.price_significance
     *
     * @param priceSignificance the value for hx_service_ticket.price_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setPriceSignificance(String priceSignificance) {
        this.priceSignificance = priceSignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_satisfaction
     *
     * @return the value of hx_service_ticket.service_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServiceSatisfaction() {
        return serviceSatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_satisfaction
     *
     * @param serviceSatisfaction the value for hx_service_ticket.service_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceSatisfaction(String serviceSatisfaction) {
        this.serviceSatisfaction = serviceSatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_significance
     *
     * @return the value of hx_service_ticket.service_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServiceSignificance() {
        return serviceSignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_significance
     *
     * @param serviceSignificance the value for hx_service_ticket.service_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceSignificance(String serviceSignificance) {
        this.serviceSignificance = serviceSignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.quality_satisfaction
     *
     * @return the value of hx_service_ticket.quality_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getQualitySatisfaction() {
        return qualitySatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.quality_satisfaction
     *
     * @param qualitySatisfaction the value for hx_service_ticket.quality_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setQualitySatisfaction(String qualitySatisfaction) {
        this.qualitySatisfaction = qualitySatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.quality_significance
     *
     * @return the value of hx_service_ticket.quality_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getQualitySignificance() {
        return qualitySignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.quality_significance
     *
     * @param qualitySignificance the value for hx_service_ticket.quality_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setQualitySignificance(String qualitySignificance) {
        this.qualitySignificance = qualitySignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.physiology_satisfaction
     *
     * @return the value of hx_service_ticket.physiology_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getPhysiologySatisfaction() {
        return physiologySatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.physiology_satisfaction
     *
     * @param physiologySatisfaction the value for hx_service_ticket.physiology_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setPhysiologySatisfaction(String physiologySatisfaction) {
        this.physiologySatisfaction = physiologySatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.physiology_significance
     *
     * @return the value of hx_service_ticket.physiology_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getPhysiologySignificance() {
        return physiologySignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.physiology_significance
     *
     * @param physiologySignificance the value for hx_service_ticket.physiology_significance
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setPhysiologySignificance(String physiologySignificance) {
        this.physiologySignificance = physiologySignificance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.customer_satisfaction
     *
     * @return the value of hx_service_ticket.customer_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCustomerSatisfaction() {
        return customerSatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.customer_satisfaction
     *
     * @param customerSatisfaction the value for hx_service_ticket.customer_satisfaction
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCustomerSatisfaction(String customerSatisfaction) {
        this.customerSatisfaction = customerSatisfaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.warranty_policy
     *
     * @return the value of hx_service_ticket.warranty_policy
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getWarrantyPolicy() {
        return warrantyPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.warranty_policy
     *
     * @param warrantyPolicy the value for hx_service_ticket.warranty_policy
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setWarrantyPolicy(String warrantyPolicy) {
        this.warrantyPolicy = warrantyPolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.is_replace_parts
     *
     * @return the value of hx_service_ticket.is_replace_parts
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Integer getIsReplaceParts() {
        return isReplaceParts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.is_replace_parts
     *
     * @param isReplaceParts the value for hx_service_ticket.is_replace_parts
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setIsReplaceParts(Integer isReplaceParts) {
        this.isReplaceParts = isReplaceParts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.manul_num
     *
     * @return the value of hx_service_ticket.manul_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getManulNum() {
        return manulNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.manul_num
     *
     * @param manulNum the value for hx_service_ticket.manul_num
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setManulNum(String manulNum) {
        this.manulNum = manulNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.is_double_install
     *
     * @return the value of hx_service_ticket.is_double_install
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getIsDoubleInstall() {
        return isDoubleInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.is_double_install
     *
     * @param isDoubleInstall the value for hx_service_ticket.is_double_install
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setIsDoubleInstall(String isDoubleInstall) {
        this.isDoubleInstall = isDoubleInstall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.input_time
     *
     * @return the value of hx_service_ticket.input_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getInputTime() {
        return inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.input_time
     *
     * @param inputTime the value for hx_service_ticket.input_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setInputTime(Date inputTime) {
        this.inputTime = inputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.appointment_install_date
     *
     * @return the value of hx_service_ticket.appointment_install_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getAppointmentInstallDate() {
        return appointmentInstallDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.appointment_install_date
     *
     * @param appointmentInstallDate the value for hx_service_ticket.appointment_install_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setAppointmentInstallDate(Date appointmentInstallDate) {
        this.appointmentInstallDate = appointmentInstallDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.move_address
     *
     * @return the value of hx_service_ticket.move_address
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getMoveAddress() {
        return moveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.move_address
     *
     * @param moveAddress the value for hx_service_ticket.move_address
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setMoveAddress(String moveAddress) {
        this.moveAddress = moveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.machine_check_fault_reason
     *
     * @return the value of hx_service_ticket.machine_check_fault_reason
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getMachineCheckFaultReason() {
        return machineCheckFaultReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.machine_check_fault_reason
     *
     * @param machineCheckFaultReason the value for hx_service_ticket.machine_check_fault_reason
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setMachineCheckFaultReason(String machineCheckFaultReason) {
        this.machineCheckFaultReason = machineCheckFaultReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.center_check_traffic_fee
     *
     * @return the value of hx_service_ticket.center_check_traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getCenterCheckTrafficFee() {
        return centerCheckTrafficFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.center_check_traffic_fee
     *
     * @param centerCheckTrafficFee the value for hx_service_ticket.center_check_traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCenterCheckTrafficFee(Float centerCheckTrafficFee) {
        this.centerCheckTrafficFee = centerCheckTrafficFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.center_check_delay_fee
     *
     * @return the value of hx_service_ticket.center_check_delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getCenterCheckDelayFee() {
        return centerCheckDelayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.center_check_delay_fee
     *
     * @param centerCheckDelayFee the value for hx_service_ticket.center_check_delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCenterCheckDelayFee(Float centerCheckDelayFee) {
        this.centerCheckDelayFee = centerCheckDelayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.center_check_other_fee
     *
     * @return the value of hx_service_ticket.center_check_other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getCenterCheckOtherFee() {
        return centerCheckOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.center_check_other_fee
     *
     * @param centerCheckOtherFee the value for hx_service_ticket.center_check_other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCenterCheckOtherFee(Float centerCheckOtherFee) {
        this.centerCheckOtherFee = centerCheckOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.center_check_man
     *
     * @return the value of hx_service_ticket.center_check_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCenterCheckMan() {
        return centerCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.center_check_man
     *
     * @param centerCheckMan the value for hx_service_ticket.center_check_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCenterCheckMan(String centerCheckMan) {
        this.centerCheckMan = centerCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.center_check_time
     *
     * @return the value of hx_service_ticket.center_check_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getCenterCheckTime() {
        return centerCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.center_check_time
     *
     * @param centerCheckTime the value for hx_service_ticket.center_check_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCenterCheckTime(Date centerCheckTime) {
        this.centerCheckTime = centerCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.center_check_result
     *
     * @return the value of hx_service_ticket.center_check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCenterCheckResult() {
        return centerCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.center_check_result
     *
     * @param centerCheckResult the value for hx_service_ticket.center_check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCenterCheckResult(String centerCheckResult) {
        this.centerCheckResult = centerCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.center_check_comment
     *
     * @return the value of hx_service_ticket.center_check_comment
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCenterCheckComment() {
        return centerCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.center_check_comment
     *
     * @param centerCheckComment the value for hx_service_ticket.center_check_comment
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCenterCheckComment(String centerCheckComment) {
        this.centerCheckComment = centerCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.headquarters_check_traffic_fee
     *
     * @return the value of hx_service_ticket.headquarters_check_traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getHeadquartersCheckTrafficFee() {
        return headquartersCheckTrafficFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.headquarters_check_traffic_fee
     *
     * @param headquartersCheckTrafficFee the value for hx_service_ticket.headquarters_check_traffic_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setHeadquartersCheckTrafficFee(Float headquartersCheckTrafficFee) {
        this.headquartersCheckTrafficFee = headquartersCheckTrafficFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.headquarters_check_delay_fee
     *
     * @return the value of hx_service_ticket.headquarters_check_delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getHeadquartersCheckDelayFee() {
        return headquartersCheckDelayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.headquarters_check_delay_fee
     *
     * @param headquartersCheckDelayFee the value for hx_service_ticket.headquarters_check_delay_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setHeadquartersCheckDelayFee(Float headquartersCheckDelayFee) {
        this.headquartersCheckDelayFee = headquartersCheckDelayFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.headquarters_check_other_fee
     *
     * @return the value of hx_service_ticket.headquarters_check_other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Float getHeadquartersCheckOtherFee() {
        return headquartersCheckOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.headquarters_check_other_fee
     *
     * @param headquartersCheckOtherFee the value for hx_service_ticket.headquarters_check_other_fee
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setHeadquartersCheckOtherFee(Float headquartersCheckOtherFee) {
        this.headquartersCheckOtherFee = headquartersCheckOtherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.headquarters_check_man
     *
     * @return the value of hx_service_ticket.headquarters_check_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getHeadquartersCheckMan() {
        return headquartersCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.headquarters_check_man
     *
     * @param headquartersCheckMan the value for hx_service_ticket.headquarters_check_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setHeadquartersCheckMan(String headquartersCheckMan) {
        this.headquartersCheckMan = headquartersCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.headquarters_check_time
     *
     * @return the value of hx_service_ticket.headquarters_check_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getHeadquartersCheckTime() {
        return headquartersCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.headquarters_check_time
     *
     * @param headquartersCheckTime the value for hx_service_ticket.headquarters_check_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setHeadquartersCheckTime(Date headquartersCheckTime) {
        this.headquartersCheckTime = headquartersCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.headquarters_check_result
     *
     * @return the value of hx_service_ticket.headquarters_check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getHeadquartersCheckResult() {
        return headquartersCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.headquarters_check_result
     *
     * @param headquartersCheckResult the value for hx_service_ticket.headquarters_check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setHeadquartersCheckResult(String headquartersCheckResult) {
        this.headquartersCheckResult = headquartersCheckResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.headquarters_check_comment
     *
     * @return the value of hx_service_ticket.headquarters_check_comment
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getHeadquartersCheckComment() {
        return headquartersCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.headquarters_check_comment
     *
     * @param headquartersCheckComment the value for hx_service_ticket.headquarters_check_comment
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setHeadquartersCheckComment(String headquartersCheckComment) {
        this.headquartersCheckComment = headquartersCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.check_result
     *
     * @return the value of hx_service_ticket.check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCheckResult() {
        return checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.check_result
     *
     * @param checkResult the value for hx_service_ticket.check_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCheckResult(String checkResult) {
        this.checkResult = checkResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.recall_man
     *
     * @return the value of hx_service_ticket.recall_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getRecallMan() {
        return recallMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.recall_man
     *
     * @param recallMan the value for hx_service_ticket.recall_man
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setRecallMan(String recallMan) {
        this.recallMan = recallMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.recall_result
     *
     * @return the value of hx_service_ticket.recall_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getRecallResult() {
        return recallResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.recall_result
     *
     * @param recallResult the value for hx_service_ticket.recall_result
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setRecallResult(String recallResult) {
        this.recallResult = recallResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.recall_time
     *
     * @return the value of hx_service_ticket.recall_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getRecallTime() {
        return recallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.recall_time
     *
     * @param recallTime the value for hx_service_ticket.recall_time
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setRecallTime(Date recallTime) {
        this.recallTime = recallTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.is_clear
     *
     * @return the value of hx_service_ticket.is_clear
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Boolean getIsClear() {
        return isClear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.is_clear
     *
     * @param isClear the value for hx_service_ticket.is_clear
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setIsClear(Boolean isClear) {
        this.isClear = isClear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_status
     *
     * @return the value of hx_service_ticket.service_status
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServiceStatus() {
        return serviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_status
     *
     * @param serviceStatus the value for hx_service_ticket.service_status
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceStatus(String serviceStatus) {
        this.serviceStatus = serviceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.center
     *
     * @return the value of hx_service_ticket.center
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCenter() {
        return center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.center
     *
     * @param center the value for hx_service_ticket.center
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCenter(String center) {
        this.center = center;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.website
     *
     * @return the value of hx_service_ticket.website
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.website
     *
     * @param website the value for hx_service_ticket.website
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.comment_s
     *
     * @return the value of hx_service_ticket.comment_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCommentS() {
        return commentS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.comment_s
     *
     * @param commentS the value for hx_service_ticket.comment_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCommentS(String commentS) {
        this.commentS = commentS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.create_man_s
     *
     * @return the value of hx_service_ticket.create_man_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCreateManS() {
        return createManS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.create_man_s
     *
     * @param createManS the value for hx_service_ticket.create_man_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCreateManS(String createManS) {
        this.createManS = createManS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.create_organization_s
     *
     * @return the value of hx_service_ticket.create_organization_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCreateOrganizationS() {
        return createOrganizationS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.create_organization_s
     *
     * @param createOrganizationS the value for hx_service_ticket.create_organization_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCreateOrganizationS(String createOrganizationS) {
        this.createOrganizationS = createOrganizationS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.create_time_s
     *
     * @return the value of hx_service_ticket.create_time_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getCreateTimeS() {
        return createTimeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.create_time_s
     *
     * @param createTimeS the value for hx_service_ticket.create_time_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCreateTimeS(Date createTimeS) {
        this.createTimeS = createTimeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.alter_man_s
     *
     * @return the value of hx_service_ticket.alter_man_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getAlterManS() {
        return alterManS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.alter_man_s
     *
     * @param alterManS the value for hx_service_ticket.alter_man_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setAlterManS(String alterManS) {
        this.alterManS = alterManS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.alter_organization_s
     *
     * @return the value of hx_service_ticket.alter_organization_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getAlterOrganizationS() {
        return alterOrganizationS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.alter_organization_s
     *
     * @param alterOrganizationS the value for hx_service_ticket.alter_organization_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setAlterOrganizationS(String alterOrganizationS) {
        this.alterOrganizationS = alterOrganizationS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.alter_time_s
     *
     * @return the value of hx_service_ticket.alter_time_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getAlterTimeS() {
        return alterTimeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.alter_time_s
     *
     * @param alterTimeS the value for hx_service_ticket.alter_time_s
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setAlterTimeS(Date alterTimeS) {
        this.alterTimeS = alterTimeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.process_instance_id
     *
     * @return the value of hx_service_ticket.process_instance_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.process_instance_id
     *
     * @param processInstanceId the value for hx_service_ticket.process_instance_id
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.applicant
     *
     * @return the value of hx_service_ticket.applicant
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.applicant
     *
     * @param applicant the value for hx_service_ticket.applicant
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.apply_date
     *
     * @return the value of hx_service_ticket.apply_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.apply_date
     *
     * @param applyDate the value for hx_service_ticket.apply_date
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.service_unit
     *
     * @return the value of hx_service_ticket.service_unit
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getServiceUnit() {
        return serviceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.service_unit
     *
     * @param serviceUnit the value for hx_service_ticket.service_unit
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setServiceUnit(String serviceUnit) {
        this.serviceUnit = serviceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.create_position
     *
     * @return the value of hx_service_ticket.create_position
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public String getCreatePosition() {
        return createPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.create_position
     *
     * @param createPosition the value for hx_service_ticket.create_position
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setCreatePosition(String createPosition) {
        this.createPosition = createPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_ticket.is_pass_check
     *
     * @return the value of hx_service_ticket.is_pass_check
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public Boolean getIsPassCheck() {
        return isPassCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_ticket.is_pass_check
     *
     * @param isPassCheck the value for hx_service_ticket.is_pass_check
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    public void setIsPassCheck(Boolean isPassCheck) {
        this.isPassCheck = isPassCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_service_ticket
     *
     * @mbggenerated Mon Dec 15 10:37:40 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serviceId=").append(serviceId);
        sb.append(", jlServiceId=").append(jlServiceId);
        sb.append(", customerId=").append(customerId);
        sb.append(", productId=").append(productId);
        sb.append(", sequence=").append(sequence);
        sb.append(", category=").append(category);
        sb.append(", serviceType=").append(serviceType);
        sb.append(", linkMan=").append(linkMan);
        sb.append(", linkPhone=").append(linkPhone);
        sb.append(", appointmentDate=").append(appointmentDate);
        sb.append(", appointmentQuantum=").append(appointmentQuantum);
        sb.append(", urgencyDegree=").append(urgencyDegree);
        sb.append(", dispatchInfo=").append(dispatchInfo);
        sb.append(", customerDescribe=").append(customerDescribe);
        sb.append(", informRepairDate=").append(informRepairDate);
        sb.append(", repairMode=").append(repairMode);
        sb.append(", moveMode=").append(moveMode);
        sb.append(", chargeFluorineNum=").append(chargeFluorineNum);
        sb.append(", distanceApplyNum=").append(distanceApplyNum);
        sb.append(", servicePattern=").append(servicePattern);
        sb.append(", serviceCardNum=").append(serviceCardNum);
        sb.append(", serviceMan=").append(serviceMan);
        sb.append(", serviceDate=").append(serviceDate);
        sb.append(", trafficFee=").append(trafficFee);
        sb.append(", delayFee=").append(delayFee);
        sb.append(", otherFee=").append(otherFee);
        sb.append(", productExteriorSatisfaction=").append(productExteriorSatisfaction);
        sb.append(", productExteriorSignificance=").append(productExteriorSignificance);
        sb.append(", priceSatisfaction=").append(priceSatisfaction);
        sb.append(", priceSignificance=").append(priceSignificance);
        sb.append(", serviceSatisfaction=").append(serviceSatisfaction);
        sb.append(", serviceSignificance=").append(serviceSignificance);
        sb.append(", qualitySatisfaction=").append(qualitySatisfaction);
        sb.append(", qualitySignificance=").append(qualitySignificance);
        sb.append(", physiologySatisfaction=").append(physiologySatisfaction);
        sb.append(", physiologySignificance=").append(physiologySignificance);
        sb.append(", customerSatisfaction=").append(customerSatisfaction);
        sb.append(", warrantyPolicy=").append(warrantyPolicy);
        sb.append(", isReplaceParts=").append(isReplaceParts);
        sb.append(", manulNum=").append(manulNum);
        sb.append(", isDoubleInstall=").append(isDoubleInstall);
        sb.append(", inputTime=").append(inputTime);
        sb.append(", appointmentInstallDate=").append(appointmentInstallDate);
        sb.append(", moveAddress=").append(moveAddress);
        sb.append(", machineCheckFaultReason=").append(machineCheckFaultReason);
        sb.append(", centerCheckTrafficFee=").append(centerCheckTrafficFee);
        sb.append(", centerCheckDelayFee=").append(centerCheckDelayFee);
        sb.append(", centerCheckOtherFee=").append(centerCheckOtherFee);
        sb.append(", centerCheckMan=").append(centerCheckMan);
        sb.append(", centerCheckTime=").append(centerCheckTime);
        sb.append(", centerCheckResult=").append(centerCheckResult);
        sb.append(", centerCheckComment=").append(centerCheckComment);
        sb.append(", headquartersCheckTrafficFee=").append(headquartersCheckTrafficFee);
        sb.append(", headquartersCheckDelayFee=").append(headquartersCheckDelayFee);
        sb.append(", headquartersCheckOtherFee=").append(headquartersCheckOtherFee);
        sb.append(", headquartersCheckMan=").append(headquartersCheckMan);
        sb.append(", headquartersCheckTime=").append(headquartersCheckTime);
        sb.append(", headquartersCheckResult=").append(headquartersCheckResult);
        sb.append(", headquartersCheckComment=").append(headquartersCheckComment);
        sb.append(", checkResult=").append(checkResult);
        sb.append(", recallMan=").append(recallMan);
        sb.append(", recallResult=").append(recallResult);
        sb.append(", recallTime=").append(recallTime);
        sb.append(", isClear=").append(isClear);
        sb.append(", serviceStatus=").append(serviceStatus);
        sb.append(", center=").append(center);
        sb.append(", website=").append(website);
        sb.append(", commentS=").append(commentS);
        sb.append(", createManS=").append(createManS);
        sb.append(", createOrganizationS=").append(createOrganizationS);
        sb.append(", createTimeS=").append(createTimeS);
        sb.append(", alterManS=").append(alterManS);
        sb.append(", alterOrganizationS=").append(alterOrganizationS);
        sb.append(", alterTimeS=").append(alterTimeS);
        sb.append(", processInstanceId=").append(processInstanceId);
        sb.append(", applicant=").append(applicant);
        sb.append(", applyDate=").append(applyDate);
        sb.append(", serviceUnit=").append(serviceUnit);
        sb.append(", createPosition=").append(createPosition);
        sb.append(", isPassCheck=").append(isPassCheck);
        sb.append("]");
        return sb.toString();
    }

	@Override
	public String getWorkEntityId() {
		return this.serviceId;
	}

	@Override
	public String getStatus() {
		return this.serviceStatus;
	}

	public BigDecimal getDataFrom() {
		return dataFrom;
	}

	public void setDataFrom(BigDecimal dataFrom) {
		this.dataFrom = dataFrom;
	}

	@Override
	public void setStatus(String status) {
		this.serviceStatus = status;
	}
}