package com.gome.gmhx.entity;

public class BarCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bar_code.bar_code
     *
     * @mbggenerated Tue Jul 29 11:38:30 CST 2014
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_bar_code.machine_type
     *
     * @mbggenerated Tue Jul 29 11:38:30 CST 2014
     */
    private String machineType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bar_code.bar_code
     *
     * @return the value of hx_bar_code.bar_code
     *
     * @mbggenerated Tue Jul 29 11:38:30 CST 2014
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bar_code.bar_code
     *
     * @param barCode the value for hx_bar_code.bar_code
     *
     * @mbggenerated Tue Jul 29 11:38:30 CST 2014
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_bar_code.machine_type
     *
     * @return the value of hx_bar_code.machine_type
     *
     * @mbggenerated Tue Jul 29 11:38:30 CST 2014
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_bar_code.machine_type
     *
     * @param machineType the value for hx_bar_code.machine_type
     *
     * @mbggenerated Tue Jul 29 11:38:30 CST 2014
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_bar_code
     *
     * @mbggenerated Tue Jul 29 11:38:30 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", barCode=").append(barCode);
        sb.append(", machineType=").append(machineType);
        sb.append("]");
        return sb.toString();
    }
}