package com.gome.gmhx.entity;

public class EccBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_brand.PRODH
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    private String prodh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_brand.STUFE
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    private String stufe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_brand.VTEXT
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    private String vtext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecc_brand.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    private String updateFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_brand.PRODH
     *
     * @return the value of ecc_brand.PRODH
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    public String getProdh() {
        return prodh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_brand.PRODH
     *
     * @param prodh the value for ecc_brand.PRODH
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    public void setProdh(String prodh) {
        this.prodh = prodh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_brand.STUFE
     *
     * @return the value of ecc_brand.STUFE
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    public String getStufe() {
        return stufe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_brand.STUFE
     *
     * @param stufe the value for ecc_brand.STUFE
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    public void setStufe(String stufe) {
        this.stufe = stufe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_brand.VTEXT
     *
     * @return the value of ecc_brand.VTEXT
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    public String getVtext() {
        return vtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_brand.VTEXT
     *
     * @param vtext the value for ecc_brand.VTEXT
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    public void setVtext(String vtext) {
        this.vtext = vtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecc_brand.UPDATE_FLAG
     *
     * @return the value of ecc_brand.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    public String getUpdateFlag() {
        return updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecc_brand.UPDATE_FLAG
     *
     * @param updateFlag the value for ecc_brand.UPDATE_FLAG
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    public void setUpdateFlag(String updateFlag) {
        this.updateFlag = updateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecc_brand
     *
     * @mbggenerated Thu Jul 31 09:20:15 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", prodh=").append(prodh);
        sb.append(", stufe=").append(stufe);
        sb.append(", vtext=").append(vtext);
        sb.append(", updateFlag=").append(updateFlag);
        sb.append("]");
        return sb.toString();
    }
}