package com.gome.gmhx.entity;

import com.gome.common.util.FDate;
import java.util.Date;

public class EmpAccountJobLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.logid
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.BatchNo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String batchno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.EmpNo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String empno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.EmpName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String empname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.AD_Account
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String adAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.AP_Account
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String apAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.CompName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String compname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.DeptCode
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String deptcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.DeptName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String deptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.PositionCode
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String positioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.PositionName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String positionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.DutyFlag
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String dutyflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.OperatorType
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String operatortype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.State
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.LogInfo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String loginfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.ErrorInfo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String errorinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.CreateDate
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.CreateTime
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.ModifyDate
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_AccountJobLog.ModifyTime
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.logid
     *
     * @return the value of t_AccountJobLog.logid
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.logid
     *
     * @param logid the value for t_AccountJobLog.logid
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setLogid(String logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.BatchNo
     *
     * @return the value of t_AccountJobLog.BatchNo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getBatchno() {
        return batchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.BatchNo
     *
     * @param batchno the value for t_AccountJobLog.BatchNo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.EmpNo
     *
     * @return the value of t_AccountJobLog.EmpNo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.EmpNo
     *
     * @param empno the value for t_AccountJobLog.EmpNo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setEmpno(String empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.EmpName
     *
     * @return the value of t_AccountJobLog.EmpName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.EmpName
     *
     * @param empname the value for t_AccountJobLog.EmpName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setEmpname(String empname) {
        this.empname = empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.AD_Account
     *
     * @return the value of t_AccountJobLog.AD_Account
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getAdAccount() {
        return adAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.AD_Account
     *
     * @param adAccount the value for t_AccountJobLog.AD_Account
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setAdAccount(String adAccount) {
        this.adAccount = adAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.AP_Account
     *
     * @return the value of t_AccountJobLog.AP_Account
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getApAccount() {
        return apAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.AP_Account
     *
     * @param apAccount the value for t_AccountJobLog.AP_Account
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setApAccount(String apAccount) {
        this.apAccount = apAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.CompName
     *
     * @return the value of t_AccountJobLog.CompName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getCompname() {
        return compname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.CompName
     *
     * @param compname the value for t_AccountJobLog.CompName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setCompname(String compname) {
        this.compname = compname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.DeptCode
     *
     * @return the value of t_AccountJobLog.DeptCode
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.DeptCode
     *
     * @param deptcode the value for t_AccountJobLog.DeptCode
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.DeptName
     *
     * @return the value of t_AccountJobLog.DeptName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.DeptName
     *
     * @param deptname the value for t_AccountJobLog.DeptName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.PositionCode
     *
     * @return the value of t_AccountJobLog.PositionCode
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getPositioncode() {
        return positioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.PositionCode
     *
     * @param positioncode the value for t_AccountJobLog.PositionCode
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setPositioncode(String positioncode) {
        this.positioncode = positioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.PositionName
     *
     * @return the value of t_AccountJobLog.PositionName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getPositionname() {
        return positionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.PositionName
     *
     * @param positionname the value for t_AccountJobLog.PositionName
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setPositionname(String positionname) {
        this.positionname = positionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.DutyFlag
     *
     * @return the value of t_AccountJobLog.DutyFlag
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getDutyflag() {
        return dutyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.DutyFlag
     *
     * @param dutyflag the value for t_AccountJobLog.DutyFlag
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setDutyflag(String dutyflag) {
        this.dutyflag = dutyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.OperatorType
     *
     * @return the value of t_AccountJobLog.OperatorType
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getOperatortype() {
        return operatortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.OperatorType
     *
     * @param operatortype the value for t_AccountJobLog.OperatorType
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setOperatortype(String operatortype) {
        this.operatortype = operatortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.State
     *
     * @return the value of t_AccountJobLog.State
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.State
     *
     * @param state the value for t_AccountJobLog.State
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.LogInfo
     *
     * @return the value of t_AccountJobLog.LogInfo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getLoginfo() {
        return loginfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.LogInfo
     *
     * @param loginfo the value for t_AccountJobLog.LogInfo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setLoginfo(String loginfo) {
        this.loginfo = loginfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.ErrorInfo
     *
     * @return the value of t_AccountJobLog.ErrorInfo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getErrorinfo() {
        return errorinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.ErrorInfo
     *
     * @param errorinfo the value for t_AccountJobLog.ErrorInfo
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setErrorinfo(String errorinfo) {
        this.errorinfo = errorinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.CreateDate
     *
     * @return the value of t_AccountJobLog.CreateDate
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.CreateDate
     *
     * @param createdate the value for t_AccountJobLog.CreateDate
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setCreatedate(String createdate) {
        this.createdate = FDate.getDate(createdate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.CreateDate
     *
     * @param createdate the value for t_AccountJobLog.CreateDate
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.CreateTime
     *
     * @return the value of t_AccountJobLog.CreateTime
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.CreateTime
     *
     * @param createtime the value for t_AccountJobLog.CreateTime
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.ModifyDate
     *
     * @return the value of t_AccountJobLog.ModifyDate
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.ModifyDate
     *
     * @param modifydate the value for t_AccountJobLog.ModifyDate
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setModifydate(String modifydate) {
        this.modifydate = FDate.getDate(modifydate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.ModifyDate
     *
     * @param modifydate the value for t_AccountJobLog.ModifyDate
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_AccountJobLog.ModifyTime
     *
     * @return the value of t_AccountJobLog.ModifyTime
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_AccountJobLog.ModifyTime
     *
     * @param modifytime the value for t_AccountJobLog.ModifyTime
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_AccountJobLog
     *
     * @mbggenerated Wed Feb 19 17:02:15 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logid=").append(logid);
        sb.append(", batchno=").append(batchno);
        sb.append(", empno=").append(empno);
        sb.append(", empname=").append(empname);
        sb.append(", adAccount=").append(adAccount);
        sb.append(", apAccount=").append(apAccount);
        sb.append(", compname=").append(compname);
        sb.append(", deptcode=").append(deptcode);
        sb.append(", deptname=").append(deptname);
        sb.append(", positioncode=").append(positioncode);
        sb.append(", positionname=").append(positionname);
        sb.append(", dutyflag=").append(dutyflag);
        sb.append(", operatortype=").append(operatortype);
        sb.append(", state=").append(state);
        sb.append(", loginfo=").append(loginfo);
        sb.append(", errorinfo=").append(errorinfo);
        sb.append(", createdate=").append(createdate);
        sb.append(", createtime=").append(createtime);
        sb.append(", modifydate=").append(modifydate);
        sb.append(", modifytime=").append(modifytime);
        sb.append("]");
        return sb.toString();
    }
}