package com.gome.gmhx.entity;

public class EmpSysVar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_SysVar.VarCode
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    private String varcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_SysVar.VarName
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    private String varname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_SysVar.VarValue
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    private String varvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_SysVar.VarDesc
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    private String vardesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_SysVar.VarRemark
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    private String varremark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_SysVar.VarCode
     *
     * @return the value of t_SysVar.VarCode
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public String getVarcode() {
        return varcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_SysVar.VarCode
     *
     * @param varcode the value for t_SysVar.VarCode
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public void setVarcode(String varcode) {
        this.varcode = varcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_SysVar.VarName
     *
     * @return the value of t_SysVar.VarName
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public String getVarname() {
        return varname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_SysVar.VarName
     *
     * @param varname the value for t_SysVar.VarName
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public void setVarname(String varname) {
        this.varname = varname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_SysVar.VarValue
     *
     * @return the value of t_SysVar.VarValue
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public String getVarvalue() {
        return varvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_SysVar.VarValue
     *
     * @param varvalue the value for t_SysVar.VarValue
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public void setVarvalue(String varvalue) {
        this.varvalue = varvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_SysVar.VarDesc
     *
     * @return the value of t_SysVar.VarDesc
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public String getVardesc() {
        return vardesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_SysVar.VarDesc
     *
     * @param vardesc the value for t_SysVar.VarDesc
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public void setVardesc(String vardesc) {
        this.vardesc = vardesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_SysVar.VarRemark
     *
     * @return the value of t_SysVar.VarRemark
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public String getVarremark() {
        return varremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_SysVar.VarRemark
     *
     * @param varremark the value for t_SysVar.VarRemark
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    public void setVarremark(String varremark) {
        this.varremark = varremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_SysVar
     *
     * @mbggenerated Wed Dec 25 14:56:27 CST 2013
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", varcode=").append(varcode);
        sb.append(", varname=").append(varname);
        sb.append(", varvalue=").append(varvalue);
        sb.append(", vardesc=").append(vardesc);
        sb.append(", varremark=").append(varremark);
        sb.append("]");
        return sb.toString();
    }
}