package com.gome.gmhx.entity;

import java.util.Date;

import com.gome.common.util.UUIDGenerator;

public class HxCodeBar {
    private String id;
    private String compareType;
    private String innerCode1;
    private String innerCode2;
    private String outerCode;
    private String innerModel1;
    private String innerModel2;
    private String outerModel;
    private String wholeModel;
    private String codeBegin;
    private String comment;
    private Date updateTime;
    private String brand;
    
    public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCompareType() {
        return compareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.compare_type
     *
     * @param compareType the value for hx_code_bar.compare_type
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setCompareType(String compareType) {
        this.compareType = compareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.inner_code1
     *
     * @return the value of hx_code_bar.inner_code1
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getInnerCode1() {
        return innerCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.inner_code1
     *
     * @param innerCode1 the value for hx_code_bar.inner_code1
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setInnerCode1(String innerCode1) {
        this.innerCode1 = innerCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.inner_code2
     *
     * @return the value of hx_code_bar.inner_code2
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getInnerCode2() {
        return innerCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.inner_code2
     *
     * @param innerCode2 the value for hx_code_bar.inner_code2
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setInnerCode2(String innerCode2) {
        this.innerCode2 = innerCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.outer_code
     *
     * @return the value of hx_code_bar.outer_code
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getOuterCode() {
        return outerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.outer_code
     *
     * @param outerCode the value for hx_code_bar.outer_code
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setOuterCode(String outerCode) {
        this.outerCode = outerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.inner_model1
     *
     * @return the value of hx_code_bar.inner_model1
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getInnerModel1() {
        return innerModel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.inner_model1
     *
     * @param innerModel1 the value for hx_code_bar.inner_model1
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setInnerModel1(String innerModel1) {
        this.innerModel1 = innerModel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.inner_model2
     *
     * @return the value of hx_code_bar.inner_model2
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getInnerModel2() {
        return innerModel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.inner_model2
     *
     * @param innerModel2 the value for hx_code_bar.inner_model2
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setInnerModel2(String innerModel2) {
        this.innerModel2 = innerModel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.outer_model
     *
     * @return the value of hx_code_bar.outer_model
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getOuterModel() {
        return outerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.outer_model
     *
     * @param outerModel the value for hx_code_bar.outer_model
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setOuterModel(String outerModel) {
        this.outerModel = outerModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.whole_model
     *
     * @return the value of hx_code_bar.whole_model
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getWholeModel() {
        return wholeModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.whole_model
     *
     * @param wholeModel the value for hx_code_bar.whole_model
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setWholeModel(String wholeModel) {
        this.wholeModel = wholeModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.code_begin
     *
     * @return the value of hx_code_bar.code_begin
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getCodeBegin() {
        return codeBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.code_begin
     *
     * @param codeBegin the value for hx_code_bar.code_begin
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setCodeBegin(String codeBegin) {
        this.codeBegin = codeBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.comment
     *
     * @return the value of hx_code_bar.comment
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.comment
     *
     * @param comment the value for hx_code_bar.comment
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_code_bar.update_time
     *
     * @return the value of hx_code_bar.update_time
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_code_bar.update_time
     *
     * @param updateTime the value for hx_code_bar.update_time
     *
     * @mbggenerated Mon Aug 11 17:35:33 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public HxCodeBar(){
		this.updateTime = new Date();
		this.id =UUIDGenerator.getUUID();
	}
}