package com.gome.gmhx.entity;

public class HxGoodbillKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.GSXX01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String gsxx01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.THDH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private Long thdh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.GSXX01
     *
     * @return the value of hx_goodbill.GSXX01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getGsxx01() {
        return gsxx01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.GSXX01
     *
     * @param gsxx01 the value for hx_goodbill.GSXX01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setGsxx01(String gsxx01) {
        this.gsxx01 = gsxx01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.THDH
     *
     * @return the value of hx_goodbill.THDH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public Long getThdh() {
        return thdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.THDH
     *
     * @param thdh the value for hx_goodbill.THDH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setThdh(Long thdh) {
        this.thdh = thdh;
    }
}