package com.gome.gmhx.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HxGoodbillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public HxGoodbillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGsxx01IsNull() {
            addCriterion("GSXX01 is null");
            return (Criteria) this;
        }

        public Criteria andGsxx01IsNotNull() {
            addCriterion("GSXX01 is not null");
            return (Criteria) this;
        }

        public Criteria andGsxx01EqualTo(String value) {
            addCriterion("GSXX01 =", value, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01NotEqualTo(String value) {
            addCriterion("GSXX01 <>", value, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01GreaterThan(String value) {
            addCriterion("GSXX01 >", value, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01GreaterThanOrEqualTo(String value) {
            addCriterion("GSXX01 >=", value, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01LessThan(String value) {
            addCriterion("GSXX01 <", value, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01LessThanOrEqualTo(String value) {
            addCriterion("GSXX01 <=", value, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01Like(String value) {
            addCriterion("GSXX01 like", value, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01NotLike(String value) {
            addCriterion("GSXX01 not like", value, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01In(List<String> values) {
            addCriterion("GSXX01 in", values, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01NotIn(List<String> values) {
            addCriterion("GSXX01 not in", values, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01Between(String value1, String value2) {
            addCriterion("GSXX01 between", value1, value2, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andGsxx01NotBetween(String value1, String value2) {
            addCriterion("GSXX01 not between", value1, value2, "gsxx01");
            return (Criteria) this;
        }

        public Criteria andThdhIsNull() {
            addCriterion("THDH is null");
            return (Criteria) this;
        }

        public Criteria andThdhIsNotNull() {
            addCriterion("THDH is not null");
            return (Criteria) this;
        }

        public Criteria andThdhEqualTo(Long value) {
            addCriterion("THDH =", value, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhNotEqualTo(Long value) {
            addCriterion("THDH <>", value, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhGreaterThan(Long value) {
            addCriterion("THDH >", value, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhGreaterThanOrEqualTo(Long value) {
            addCriterion("THDH >=", value, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhLessThan(Long value) {
            addCriterion("THDH <", value, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhLessThanOrEqualTo(Long value) {
            addCriterion("THDH <=", value, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhIn(List<Long> values) {
            addCriterion("THDH in", values, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhNotIn(List<Long> values) {
            addCriterion("THDH not in", values, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhBetween(Long value1, Long value2) {
            addCriterion("THDH between", value1, value2, "thdh");
            return (Criteria) this;
        }

        public Criteria andThdhNotBetween(Long value1, Long value2) {
            addCriterion("THDH not between", value1, value2, "thdh");
            return (Criteria) this;
        }

        public Criteria andGsmcIsNull() {
            addCriterion("GSMC is null");
            return (Criteria) this;
        }

        public Criteria andGsmcIsNotNull() {
            addCriterion("GSMC is not null");
            return (Criteria) this;
        }

        public Criteria andGsmcEqualTo(String value) {
            addCriterion("GSMC =", value, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcNotEqualTo(String value) {
            addCriterion("GSMC <>", value, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcGreaterThan(String value) {
            addCriterion("GSMC >", value, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcGreaterThanOrEqualTo(String value) {
            addCriterion("GSMC >=", value, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcLessThan(String value) {
            addCriterion("GSMC <", value, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcLessThanOrEqualTo(String value) {
            addCriterion("GSMC <=", value, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcLike(String value) {
            addCriterion("GSMC like", value, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcNotLike(String value) {
            addCriterion("GSMC not like", value, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcIn(List<String> values) {
            addCriterion("GSMC in", values, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcNotIn(List<String> values) {
            addCriterion("GSMC not in", values, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcBetween(String value1, String value2) {
            addCriterion("GSMC between", value1, value2, "gsmc");
            return (Criteria) this;
        }

        public Criteria andGsmcNotBetween(String value1, String value2) {
            addCriterion("GSMC not between", value1, value2, "gsmc");
            return (Criteria) this;
        }

        public Criteria andKhmcIsNull() {
            addCriterion("KHMC is null");
            return (Criteria) this;
        }

        public Criteria andKhmcIsNotNull() {
            addCriterion("KHMC is not null");
            return (Criteria) this;
        }

        public Criteria andKhmcEqualTo(String value) {
            addCriterion("KHMC =", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcNotEqualTo(String value) {
            addCriterion("KHMC <>", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcGreaterThan(String value) {
            addCriterion("KHMC >", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcGreaterThanOrEqualTo(String value) {
            addCriterion("KHMC >=", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcLessThan(String value) {
            addCriterion("KHMC <", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcLessThanOrEqualTo(String value) {
            addCriterion("KHMC <=", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcLike(String value) {
            addCriterion("KHMC like", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcNotLike(String value) {
            addCriterion("KHMC not like", value, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcIn(List<String> values) {
            addCriterion("KHMC in", values, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcNotIn(List<String> values) {
            addCriterion("KHMC not in", values, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcBetween(String value1, String value2) {
            addCriterion("KHMC between", value1, value2, "khmc");
            return (Criteria) this;
        }

        public Criteria andKhmcNotBetween(String value1, String value2) {
            addCriterion("KHMC not between", value1, value2, "khmc");
            return (Criteria) this;
        }

        public Criteria andFphIsNull() {
            addCriterion("FPH is null");
            return (Criteria) this;
        }

        public Criteria andFphIsNotNull() {
            addCriterion("FPH is not null");
            return (Criteria) this;
        }

        public Criteria andFphEqualTo(String value) {
            addCriterion("FPH =", value, "fph");
            return (Criteria) this;
        }

        public Criteria andFphNotEqualTo(String value) {
            addCriterion("FPH <>", value, "fph");
            return (Criteria) this;
        }

        public Criteria andFphGreaterThan(String value) {
            addCriterion("FPH >", value, "fph");
            return (Criteria) this;
        }

        public Criteria andFphGreaterThanOrEqualTo(String value) {
            addCriterion("FPH >=", value, "fph");
            return (Criteria) this;
        }

        public Criteria andFphLessThan(String value) {
            addCriterion("FPH <", value, "fph");
            return (Criteria) this;
        }

        public Criteria andFphLessThanOrEqualTo(String value) {
            addCriterion("FPH <=", value, "fph");
            return (Criteria) this;
        }

        public Criteria andFphLike(String value) {
            addCriterion("FPH like", value, "fph");
            return (Criteria) this;
        }

        public Criteria andFphNotLike(String value) {
            addCriterion("FPH not like", value, "fph");
            return (Criteria) this;
        }

        public Criteria andFphIn(List<String> values) {
            addCriterion("FPH in", values, "fph");
            return (Criteria) this;
        }

        public Criteria andFphNotIn(List<String> values) {
            addCriterion("FPH not in", values, "fph");
            return (Criteria) this;
        }

        public Criteria andFphBetween(String value1, String value2) {
            addCriterion("FPH between", value1, value2, "fph");
            return (Criteria) this;
        }

        public Criteria andFphNotBetween(String value1, String value2) {
            addCriterion("FPH not between", value1, value2, "fph");
            return (Criteria) this;
        }

        public Criteria andJzrqIsNull() {
            addCriterion("JZRQ is null");
            return (Criteria) this;
        }

        public Criteria andJzrqIsNotNull() {
            addCriterion("JZRQ is not null");
            return (Criteria) this;
        }

        public Criteria andJzrqEqualTo(Date value) {
            addCriterion("JZRQ =", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqNotEqualTo(Date value) {
            addCriterion("JZRQ <>", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqGreaterThan(Date value) {
            addCriterion("JZRQ >", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqGreaterThanOrEqualTo(Date value) {
            addCriterion("JZRQ >=", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqLessThan(Date value) {
            addCriterion("JZRQ <", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqLessThanOrEqualTo(Date value) {
            addCriterion("JZRQ <=", value, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqIn(List<Date> values) {
            addCriterion("JZRQ in", values, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqNotIn(List<Date> values) {
            addCriterion("JZRQ not in", values, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqBetween(Date value1, Date value2) {
            addCriterion("JZRQ between", value1, value2, "jzrq");
            return (Criteria) this;
        }

        public Criteria andJzrqNotBetween(Date value1, Date value2) {
            addCriterion("JZRQ not between", value1, value2, "jzrq");
            return (Criteria) this;
        }

        public Criteria andYyydmIsNull() {
            addCriterion("YYYDM is null");
            return (Criteria) this;
        }

        public Criteria andYyydmIsNotNull() {
            addCriterion("YYYDM is not null");
            return (Criteria) this;
        }

        public Criteria andYyydmEqualTo(String value) {
            addCriterion("YYYDM =", value, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmNotEqualTo(String value) {
            addCriterion("YYYDM <>", value, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmGreaterThan(String value) {
            addCriterion("YYYDM >", value, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmGreaterThanOrEqualTo(String value) {
            addCriterion("YYYDM >=", value, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmLessThan(String value) {
            addCriterion("YYYDM <", value, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmLessThanOrEqualTo(String value) {
            addCriterion("YYYDM <=", value, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmLike(String value) {
            addCriterion("YYYDM like", value, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmNotLike(String value) {
            addCriterion("YYYDM not like", value, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmIn(List<String> values) {
            addCriterion("YYYDM in", values, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmNotIn(List<String> values) {
            addCriterion("YYYDM not in", values, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmBetween(String value1, String value2) {
            addCriterion("YYYDM between", value1, value2, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyydmNotBetween(String value1, String value2) {
            addCriterion("YYYDM not between", value1, value2, "yyydm");
            return (Criteria) this;
        }

        public Criteria andYyymcIsNull() {
            addCriterion("YYYMC is null");
            return (Criteria) this;
        }

        public Criteria andYyymcIsNotNull() {
            addCriterion("YYYMC is not null");
            return (Criteria) this;
        }

        public Criteria andYyymcEqualTo(String value) {
            addCriterion("YYYMC =", value, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcNotEqualTo(String value) {
            addCriterion("YYYMC <>", value, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcGreaterThan(String value) {
            addCriterion("YYYMC >", value, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcGreaterThanOrEqualTo(String value) {
            addCriterion("YYYMC >=", value, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcLessThan(String value) {
            addCriterion("YYYMC <", value, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcLessThanOrEqualTo(String value) {
            addCriterion("YYYMC <=", value, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcLike(String value) {
            addCriterion("YYYMC like", value, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcNotLike(String value) {
            addCriterion("YYYMC not like", value, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcIn(List<String> values) {
            addCriterion("YYYMC in", values, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcNotIn(List<String> values) {
            addCriterion("YYYMC not in", values, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcBetween(String value1, String value2) {
            addCriterion("YYYMC between", value1, value2, "yyymc");
            return (Criteria) this;
        }

        public Criteria andYyymcNotBetween(String value1, String value2) {
            addCriterion("YYYMC not between", value1, value2, "yyymc");
            return (Criteria) this;
        }

        public Criteria andXsjeIsNull() {
            addCriterion("XSJE is null");
            return (Criteria) this;
        }

        public Criteria andXsjeIsNotNull() {
            addCriterion("XSJE is not null");
            return (Criteria) this;
        }

        public Criteria andXsjeEqualTo(BigDecimal value) {
            addCriterion("XSJE =", value, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeNotEqualTo(BigDecimal value) {
            addCriterion("XSJE <>", value, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeGreaterThan(BigDecimal value) {
            addCriterion("XSJE >", value, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("XSJE >=", value, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeLessThan(BigDecimal value) {
            addCriterion("XSJE <", value, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("XSJE <=", value, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeIn(List<BigDecimal> values) {
            addCriterion("XSJE in", values, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeNotIn(List<BigDecimal> values) {
            addCriterion("XSJE not in", values, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XSJE between", value1, value2, "xsje");
            return (Criteria) this;
        }

        public Criteria andXsjeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("XSJE not between", value1, value2, "xsje");
            return (Criteria) this;
        }

        public Criteria andSpbmIsNull() {
            addCriterion("SPBM is null");
            return (Criteria) this;
        }

        public Criteria andSpbmIsNotNull() {
            addCriterion("SPBM is not null");
            return (Criteria) this;
        }

        public Criteria andSpbmEqualTo(String value) {
            addCriterion("SPBM =", value, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmNotEqualTo(String value) {
            addCriterion("SPBM <>", value, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmGreaterThan(String value) {
            addCriterion("SPBM >", value, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmGreaterThanOrEqualTo(String value) {
            addCriterion("SPBM >=", value, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmLessThan(String value) {
            addCriterion("SPBM <", value, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmLessThanOrEqualTo(String value) {
            addCriterion("SPBM <=", value, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmLike(String value) {
            addCriterion("SPBM like", value, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmNotLike(String value) {
            addCriterion("SPBM not like", value, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmIn(List<String> values) {
            addCriterion("SPBM in", values, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmNotIn(List<String> values) {
            addCriterion("SPBM not in", values, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmBetween(String value1, String value2) {
            addCriterion("SPBM between", value1, value2, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpbmNotBetween(String value1, String value2) {
            addCriterion("SPBM not between", value1, value2, "spbm");
            return (Criteria) this;
        }

        public Criteria andSpmcIsNull() {
            addCriterion("SPMC is null");
            return (Criteria) this;
        }

        public Criteria andSpmcIsNotNull() {
            addCriterion("SPMC is not null");
            return (Criteria) this;
        }

        public Criteria andSpmcEqualTo(String value) {
            addCriterion("SPMC =", value, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcNotEqualTo(String value) {
            addCriterion("SPMC <>", value, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcGreaterThan(String value) {
            addCriterion("SPMC >", value, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcGreaterThanOrEqualTo(String value) {
            addCriterion("SPMC >=", value, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcLessThan(String value) {
            addCriterion("SPMC <", value, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcLessThanOrEqualTo(String value) {
            addCriterion("SPMC <=", value, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcLike(String value) {
            addCriterion("SPMC like", value, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcNotLike(String value) {
            addCriterion("SPMC not like", value, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcIn(List<String> values) {
            addCriterion("SPMC in", values, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcNotIn(List<String> values) {
            addCriterion("SPMC not in", values, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcBetween(String value1, String value2) {
            addCriterion("SPMC between", value1, value2, "spmc");
            return (Criteria) this;
        }

        public Criteria andSpmcNotBetween(String value1, String value2) {
            addCriterion("SPMC not between", value1, value2, "spmc");
            return (Criteria) this;
        }

        public Criteria andDzbm01IsNull() {
            addCriterion("DZBM01 is null");
            return (Criteria) this;
        }

        public Criteria andDzbm01IsNotNull() {
            addCriterion("DZBM01 is not null");
            return (Criteria) this;
        }

        public Criteria andDzbm01EqualTo(String value) {
            addCriterion("DZBM01 =", value, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01NotEqualTo(String value) {
            addCriterion("DZBM01 <>", value, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01GreaterThan(String value) {
            addCriterion("DZBM01 >", value, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01GreaterThanOrEqualTo(String value) {
            addCriterion("DZBM01 >=", value, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01LessThan(String value) {
            addCriterion("DZBM01 <", value, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01LessThanOrEqualTo(String value) {
            addCriterion("DZBM01 <=", value, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01Like(String value) {
            addCriterion("DZBM01 like", value, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01NotLike(String value) {
            addCriterion("DZBM01 not like", value, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01In(List<String> values) {
            addCriterion("DZBM01 in", values, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01NotIn(List<String> values) {
            addCriterion("DZBM01 not in", values, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01Between(String value1, String value2) {
            addCriterion("DZBM01 between", value1, value2, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andDzbm01NotBetween(String value1, String value2) {
            addCriterion("DZBM01 not between", value1, value2, "dzbm01");
            return (Criteria) this;
        }

        public Criteria andBmmcIsNull() {
            addCriterion("BMMC is null");
            return (Criteria) this;
        }

        public Criteria andBmmcIsNotNull() {
            addCriterion("BMMC is not null");
            return (Criteria) this;
        }

        public Criteria andBmmcEqualTo(String value) {
            addCriterion("BMMC =", value, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcNotEqualTo(String value) {
            addCriterion("BMMC <>", value, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcGreaterThan(String value) {
            addCriterion("BMMC >", value, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcGreaterThanOrEqualTo(String value) {
            addCriterion("BMMC >=", value, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcLessThan(String value) {
            addCriterion("BMMC <", value, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcLessThanOrEqualTo(String value) {
            addCriterion("BMMC <=", value, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcLike(String value) {
            addCriterion("BMMC like", value, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcNotLike(String value) {
            addCriterion("BMMC not like", value, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcIn(List<String> values) {
            addCriterion("BMMC in", values, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcNotIn(List<String> values) {
            addCriterion("BMMC not in", values, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcBetween(String value1, String value2) {
            addCriterion("BMMC between", value1, value2, "bmmc");
            return (Criteria) this;
        }

        public Criteria andBmmcNotBetween(String value1, String value2) {
            addCriterion("BMMC not between", value1, value2, "bmmc");
            return (Criteria) this;
        }

        public Criteria andSpfl01IsNull() {
            addCriterion("SPFL01 is null");
            return (Criteria) this;
        }

        public Criteria andSpfl01IsNotNull() {
            addCriterion("SPFL01 is not null");
            return (Criteria) this;
        }

        public Criteria andSpfl01EqualTo(String value) {
            addCriterion("SPFL01 =", value, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01NotEqualTo(String value) {
            addCriterion("SPFL01 <>", value, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01GreaterThan(String value) {
            addCriterion("SPFL01 >", value, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01GreaterThanOrEqualTo(String value) {
            addCriterion("SPFL01 >=", value, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01LessThan(String value) {
            addCriterion("SPFL01 <", value, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01LessThanOrEqualTo(String value) {
            addCriterion("SPFL01 <=", value, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01Like(String value) {
            addCriterion("SPFL01 like", value, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01NotLike(String value) {
            addCriterion("SPFL01 not like", value, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01In(List<String> values) {
            addCriterion("SPFL01 in", values, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01NotIn(List<String> values) {
            addCriterion("SPFL01 not in", values, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01Between(String value1, String value2) {
            addCriterion("SPFL01 between", value1, value2, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpfl01NotBetween(String value1, String value2) {
            addCriterion("SPFL01 not between", value1, value2, "spfl01");
            return (Criteria) this;
        }

        public Criteria andSpflmcIsNull() {
            addCriterion("SPFLMC is null");
            return (Criteria) this;
        }

        public Criteria andSpflmcIsNotNull() {
            addCriterion("SPFLMC is not null");
            return (Criteria) this;
        }

        public Criteria andSpflmcEqualTo(String value) {
            addCriterion("SPFLMC =", value, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcNotEqualTo(String value) {
            addCriterion("SPFLMC <>", value, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcGreaterThan(String value) {
            addCriterion("SPFLMC >", value, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcGreaterThanOrEqualTo(String value) {
            addCriterion("SPFLMC >=", value, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcLessThan(String value) {
            addCriterion("SPFLMC <", value, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcLessThanOrEqualTo(String value) {
            addCriterion("SPFLMC <=", value, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcLike(String value) {
            addCriterion("SPFLMC like", value, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcNotLike(String value) {
            addCriterion("SPFLMC not like", value, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcIn(List<String> values) {
            addCriterion("SPFLMC in", values, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcNotIn(List<String> values) {
            addCriterion("SPFLMC not in", values, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcBetween(String value1, String value2) {
            addCriterion("SPFLMC between", value1, value2, "spflmc");
            return (Criteria) this;
        }

        public Criteria andSpflmcNotBetween(String value1, String value2) {
            addCriterion("SPFLMC not between", value1, value2, "spflmc");
            return (Criteria) this;
        }

        public Criteria andPpb01IsNull() {
            addCriterion("PPB01 is null");
            return (Criteria) this;
        }

        public Criteria andPpb01IsNotNull() {
            addCriterion("PPB01 is not null");
            return (Criteria) this;
        }

        public Criteria andPpb01EqualTo(String value) {
            addCriterion("PPB01 =", value, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01NotEqualTo(String value) {
            addCriterion("PPB01 <>", value, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01GreaterThan(String value) {
            addCriterion("PPB01 >", value, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01GreaterThanOrEqualTo(String value) {
            addCriterion("PPB01 >=", value, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01LessThan(String value) {
            addCriterion("PPB01 <", value, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01LessThanOrEqualTo(String value) {
            addCriterion("PPB01 <=", value, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01Like(String value) {
            addCriterion("PPB01 like", value, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01NotLike(String value) {
            addCriterion("PPB01 not like", value, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01In(List<String> values) {
            addCriterion("PPB01 in", values, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01NotIn(List<String> values) {
            addCriterion("PPB01 not in", values, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01Between(String value1, String value2) {
            addCriterion("PPB01 between", value1, value2, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpb01NotBetween(String value1, String value2) {
            addCriterion("PPB01 not between", value1, value2, "ppb01");
            return (Criteria) this;
        }

        public Criteria andPpbmcIsNull() {
            addCriterion("PPBMC is null");
            return (Criteria) this;
        }

        public Criteria andPpbmcIsNotNull() {
            addCriterion("PPBMC is not null");
            return (Criteria) this;
        }

        public Criteria andPpbmcEqualTo(String value) {
            addCriterion("PPBMC =", value, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcNotEqualTo(String value) {
            addCriterion("PPBMC <>", value, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcGreaterThan(String value) {
            addCriterion("PPBMC >", value, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcGreaterThanOrEqualTo(String value) {
            addCriterion("PPBMC >=", value, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcLessThan(String value) {
            addCriterion("PPBMC <", value, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcLessThanOrEqualTo(String value) {
            addCriterion("PPBMC <=", value, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcLike(String value) {
            addCriterion("PPBMC like", value, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcNotLike(String value) {
            addCriterion("PPBMC not like", value, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcIn(List<String> values) {
            addCriterion("PPBMC in", values, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcNotIn(List<String> values) {
            addCriterion("PPBMC not in", values, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcBetween(String value1, String value2) {
            addCriterion("PPBMC between", value1, value2, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andPpbmcNotBetween(String value1, String value2) {
            addCriterion("PPBMC not between", value1, value2, "ppbmc");
            return (Criteria) this;
        }

        public Criteria andZpbjIsNull() {
            addCriterion("ZPBJ is null");
            return (Criteria) this;
        }

        public Criteria andZpbjIsNotNull() {
            addCriterion("ZPBJ is not null");
            return (Criteria) this;
        }

        public Criteria andZpbjEqualTo(Integer value) {
            addCriterion("ZPBJ =", value, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjNotEqualTo(Integer value) {
            addCriterion("ZPBJ <>", value, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjGreaterThan(Integer value) {
            addCriterion("ZPBJ >", value, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjGreaterThanOrEqualTo(Integer value) {
            addCriterion("ZPBJ >=", value, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjLessThan(Integer value) {
            addCriterion("ZPBJ <", value, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjLessThanOrEqualTo(Integer value) {
            addCriterion("ZPBJ <=", value, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjIn(List<Integer> values) {
            addCriterion("ZPBJ in", values, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjNotIn(List<Integer> values) {
            addCriterion("ZPBJ not in", values, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjBetween(Integer value1, Integer value2) {
            addCriterion("ZPBJ between", value1, value2, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpbjNotBetween(Integer value1, Integer value2) {
            addCriterion("ZPBJ not between", value1, value2, "zpbj");
            return (Criteria) this;
        }

        public Criteria andZpThdhIsNull() {
            addCriterion("ZP_THDH is null");
            return (Criteria) this;
        }

        public Criteria andZpThdhIsNotNull() {
            addCriterion("ZP_THDH is not null");
            return (Criteria) this;
        }

        public Criteria andZpThdhEqualTo(Long value) {
            addCriterion("ZP_THDH =", value, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhNotEqualTo(Long value) {
            addCriterion("ZP_THDH <>", value, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhGreaterThan(Long value) {
            addCriterion("ZP_THDH >", value, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhGreaterThanOrEqualTo(Long value) {
            addCriterion("ZP_THDH >=", value, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhLessThan(Long value) {
            addCriterion("ZP_THDH <", value, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhLessThanOrEqualTo(Long value) {
            addCriterion("ZP_THDH <=", value, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhIn(List<Long> values) {
            addCriterion("ZP_THDH in", values, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhNotIn(List<Long> values) {
            addCriterion("ZP_THDH not in", values, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhBetween(Long value1, Long value2) {
            addCriterion("ZP_THDH between", value1, value2, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andZpThdhNotBetween(Long value1, Long value2) {
            addCriterion("ZP_THDH not between", value1, value2, "zpThdh");
            return (Criteria) this;
        }

        public Criteria andShuliangIsNull() {
            addCriterion("SHULIANG is null");
            return (Criteria) this;
        }

        public Criteria andShuliangIsNotNull() {
            addCriterion("SHULIANG is not null");
            return (Criteria) this;
        }

        public Criteria andShuliangEqualTo(Long value) {
            addCriterion("SHULIANG =", value, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangNotEqualTo(Long value) {
            addCriterion("SHULIANG <>", value, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangGreaterThan(Long value) {
            addCriterion("SHULIANG >", value, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangGreaterThanOrEqualTo(Long value) {
            addCriterion("SHULIANG >=", value, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangLessThan(Long value) {
            addCriterion("SHULIANG <", value, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangLessThanOrEqualTo(Long value) {
            addCriterion("SHULIANG <=", value, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangIn(List<Long> values) {
            addCriterion("SHULIANG in", values, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangNotIn(List<Long> values) {
            addCriterion("SHULIANG not in", values, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangBetween(Long value1, Long value2) {
            addCriterion("SHULIANG between", value1, value2, "shuliang");
            return (Criteria) this;
        }

        public Criteria andShuliangNotBetween(Long value1, Long value2) {
            addCriterion("SHULIANG not between", value1, value2, "shuliang");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hx_goodbill
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 27 18:18:34 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hx_goodbill
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}