package com.gome.gmhx.entity;

public class HxRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_role.role_id
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_role.role_name
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_role.role_desc
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_role.role_type
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    private String roleType;
    
    private String codeValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_role.role_id
     *
     * @return the value of hx_role.role_id
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_role.role_id
     *
     * @param roleId the value for hx_role.role_id
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_role.role_name
     *
     * @return the value of hx_role.role_name
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_role.role_name
     *
     * @param roleName the value for hx_role.role_name
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_role.role_desc
     *
     * @return the value of hx_role.role_desc
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_role.role_desc
     *
     * @param roleDesc the value for hx_role.role_desc
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_role.role_type
     *
     * @return the value of hx_role.role_type
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_role.role_type
     *
     * @param roleType the value for hx_role.role_type
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_role
     *
     * @mbggenerated Wed Jul 16 09:10:07 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", roleName=").append(roleName);
        sb.append(", roleDesc=").append(roleDesc);
        sb.append(", roleType=").append(roleType);
        sb.append("]");
        return sb.toString();
    }

	public String getCodeValue() {
		return codeValue;
	}

	public void setCodeValue(String codeValue) {
		this.codeValue = codeValue;
	}
    
    
}