package com.gome.gmhx.entity;

public class HxRoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_role_menu.role_id
     *
     * @mbggenerated Fri Jul 18 14:26:16 CST 2014
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_role_menu.menu_id
     *
     * @mbggenerated Fri Jul 18 14:26:16 CST 2014
     */
    private String menuId;
    
    private String fittingAuthId;
    
    private String roleCategoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_role_menu.role_id
     *
     * @return the value of hx_role_menu.role_id
     *
     * @mbggenerated Fri Jul 18 14:26:16 CST 2014
     */
    
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_role_menu.role_id
     *
     * @param roleId the value for hx_role_menu.role_id
     *
     * @mbggenerated Fri Jul 18 14:26:16 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_role_menu.menu_id
     *
     * @return the value of hx_role_menu.menu_id
     *
     * @mbggenerated Fri Jul 18 14:26:16 CST 2014
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_role_menu.menu_id
     *
     * @param menuId the value for hx_role_menu.menu_id
     *
     * @mbggenerated Fri Jul 18 14:26:16 CST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_role_menu
     *
     * @mbggenerated Fri Jul 18 14:26:16 CST 2014
     */
    
    public String getFittingAuthId() {
		return fittingAuthId;
	}

	public void setFittingAuthId(String fittingAuthId) {
		this.fittingAuthId = fittingAuthId;
	}

	public String getRoleCategoryId() {
		return roleCategoryId;
	}

	public void setRoleCategoryId(String roleCategoryId) {
		this.roleCategoryId = roleCategoryId;
	}
}