package com.gome.gmhx.entity;

import java.util.Date;

public class HxSettlementDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.settlement_id
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private String settlementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.service_id
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private String serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.service_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private String serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.category
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.brand
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.machine_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private String machineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.recall_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private String recallType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.service_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private Float serviceFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.settlement_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private Float settlementFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.examine_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private Float examineFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.management_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private Float managementFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.comment
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_settlement_detail_install.year_month
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    private Date createMonth;
    
    private Boolean isEffictive;

    public Boolean getIsEffictive() {
		return isEffictive;
	}

	public void setIsEffictive(Boolean isEffictive) {
		this.isEffictive = isEffictive;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.settlement_id
     *
     * @return the value of hx_settlement_detail_install.settlement_id
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public String getSettlementId() {
        return settlementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.settlement_id
     *
     * @param settlementId the value for hx_settlement_detail_install.settlement_id
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setSettlementId(String settlementId) {
        this.settlementId = settlementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.service_id
     *
     * @return the value of hx_settlement_detail_install.service_id
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.service_id
     *
     * @param serviceId the value for hx_settlement_detail_install.service_id
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.service_type
     *
     * @return the value of hx_settlement_detail_install.service_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.service_type
     *
     * @param serviceType the value for hx_settlement_detail_install.service_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.category
     *
     * @return the value of hx_settlement_detail_install.category
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.category
     *
     * @param category the value for hx_settlement_detail_install.category
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.brand
     *
     * @return the value of hx_settlement_detail_install.brand
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.brand
     *
     * @param brand the value for hx_settlement_detail_install.brand
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.machine_type
     *
     * @return the value of hx_settlement_detail_install.machine_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.machine_type
     *
     * @param machineType the value for hx_settlement_detail_install.machine_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.recall_type
     *
     * @return the value of hx_settlement_detail_install.recall_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public String getRecallType() {
        return recallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.recall_type
     *
     * @param recallType the value for hx_settlement_detail_install.recall_type
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setRecallType(String recallType) {
        this.recallType = recallType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.service_fee
     *
     * @return the value of hx_settlement_detail_install.service_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public Float getServiceFee() {
        return serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.service_fee
     *
     * @param serviceFee the value for hx_settlement_detail_install.service_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setServiceFee(Float serviceFee) {
        this.serviceFee = serviceFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.settlement_fee
     *
     * @return the value of hx_settlement_detail_install.settlement_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public Float getSettlementFee() {
        return settlementFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.settlement_fee
     *
     * @param settlementFee the value for hx_settlement_detail_install.settlement_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setSettlementFee(Float settlementFee) {
        this.settlementFee = settlementFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.examine_fee
     *
     * @return the value of hx_settlement_detail_install.examine_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public Float getExamineFee() {
        return examineFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.examine_fee
     *
     * @param examineFee the value for hx_settlement_detail_install.examine_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setExamineFee(Float examineFee) {
        this.examineFee = examineFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.management_fee
     *
     * @return the value of hx_settlement_detail_install.management_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public Float getManagementFee() {
        return managementFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.management_fee
     *
     * @param managementFee the value for hx_settlement_detail_install.management_fee
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setManagementFee(Float managementFee) {
        this.managementFee = managementFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.comment
     *
     * @return the value of hx_settlement_detail_install.comment
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.comment
     *
     * @param comment the value for hx_settlement_detail_install.comment
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_settlement_detail_install.year_month
     *
     * @return the value of hx_settlement_detail_install.year_month
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public Date getCreateMonth() {
        return createMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_settlement_detail_install.year_month
     *
     * @param yearMonth the value for hx_settlement_detail_install.year_month
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    public void setCreateMonth(Date createMonth) {
        this.createMonth = createMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_settlement_detail_install
     *
     * @mbggenerated Tue Nov 25 15:02:03 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", settlementId=").append(settlementId);
        sb.append(", serviceId=").append(serviceId);
        sb.append(", serviceType=").append(serviceType);
        sb.append(", category=").append(category);
        sb.append(", brand=").append(brand);
        sb.append(", machineType=").append(machineType);
        sb.append(", recallType=").append(recallType);
        sb.append(", serviceFee=").append(serviceFee);
        sb.append(", settlementFee=").append(settlementFee);
        sb.append(", examineFee=").append(examineFee);
        sb.append(", managementFee=").append(managementFee);
        sb.append(", comment=").append(comment);
        sb.append(", createMonth=").append(createMonth);
        sb.append("]");
        return sb.toString();
    }
}