package com.gome.gmhx.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class HxServicePartsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.repair_id
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private String repairId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.fit_machine_type
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private String fitMachineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.parts_code
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private String partsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.parts_name
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private String partsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.price
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.amount
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.old_parts_code
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private String oldPartsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.old_parts_price
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private BigDecimal oldPartsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.record_man
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    private String recordMan;
    
    private Integer term;

    public Integer getTerm() {
		return term;
	}

	public void setTerm(Integer term) {
		this.term = term;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_parts_info.record_time
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.repair_id
     *
     * @return the value of hx_service_parts_info.repair_id
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public String getRepairId() {
        return repairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.repair_id
     *
     * @param repairId the value for hx_service_parts_info.repair_id
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setRepairId(String repairId) {
        this.repairId = repairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.fit_machine_type
     *
     * @return the value of hx_service_parts_info.fit_machine_type
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public String getFitMachineType() {
        return fitMachineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.fit_machine_type
     *
     * @param fitMachineType the value for hx_service_parts_info.fit_machine_type
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setFitMachineType(String fitMachineType) {
        this.fitMachineType = fitMachineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.parts_code
     *
     * @return the value of hx_service_parts_info.parts_code
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public String getPartsCode() {
        return partsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.parts_code
     *
     * @param partsCode the value for hx_service_parts_info.parts_code
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setPartsCode(String partsCode) {
        this.partsCode = partsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.parts_name
     *
     * @return the value of hx_service_parts_info.parts_name
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public String getPartsName() {
        return partsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.parts_name
     *
     * @param partsName the value for hx_service_parts_info.parts_name
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setPartsName(String partsName) {
        this.partsName = partsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.price
     *
     * @return the value of hx_service_parts_info.price
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.price
     *
     * @param price the value for hx_service_parts_info.price
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.amount
     *
     * @return the value of hx_service_parts_info.amount
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.amount
     *
     * @param amount the value for hx_service_parts_info.amount
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.old_parts_code
     *
     * @return the value of hx_service_parts_info.old_parts_code
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public String getOldPartsCode() {
        return oldPartsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.old_parts_code
     *
     * @param oldPartsCode the value for hx_service_parts_info.old_parts_code
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setOldPartsCode(String oldPartsCode) {
        this.oldPartsCode = oldPartsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.old_parts_price
     *
     * @return the value of hx_service_parts_info.old_parts_price
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public BigDecimal getOldPartsPrice() {
        return oldPartsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.old_parts_price
     *
     * @param oldPartsPrice the value for hx_service_parts_info.old_parts_price
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setOldPartsPrice(BigDecimal oldPartsPrice) {
        this.oldPartsPrice = oldPartsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.record_man
     *
     * @return the value of hx_service_parts_info.record_man
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public String getRecordMan() {
        return recordMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.record_man
     *
     * @param recordMan the value for hx_service_parts_info.record_man
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setRecordMan(String recordMan) {
        this.recordMan = recordMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_parts_info.record_time
     *
     * @return the value of hx_service_parts_info.record_time
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_parts_info.record_time
     *
     * @param recordTime the value for hx_service_parts_info.record_time
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_service_parts_info
     *
     * @mbggenerated Fri Aug 29 14:58:49 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", repairId=").append(repairId);
        sb.append(", fitMachineType=").append(fitMachineType);
        sb.append(", partsCode=").append(partsCode);
        sb.append(", partsName=").append(partsName);
        sb.append(", price=").append(price);
        sb.append(", amount=").append(amount);
        sb.append(", oldPartsCode=").append(oldPartsCode);
        sb.append(", oldPartsPrice=").append(oldPartsPrice);
        sb.append(", recordMan=").append(recordMan);
        sb.append(", recordTime=").append(recordTime);
        sb.append("]");
        return sb.toString();
    }
}