package com.gome.gmhx.entity;

public class HxServiceTroubleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_trouble_info.repair_id
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    private String repairId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_trouble_info.trouble_code
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    private String troubleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_trouble_info.repair_content
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    private String repairContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_trouble_info.trouble_reason
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    private String troubleReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_trouble_info.trouble_description
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    private String troubleDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_trouble_info.repair_id
     *
     * @return the value of hx_service_trouble_info.repair_id
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public String getRepairId() {
        return repairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_trouble_info.repair_id
     *
     * @param repairId the value for hx_service_trouble_info.repair_id
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public void setRepairId(String repairId) {
        this.repairId = repairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_trouble_info.trouble_code
     *
     * @return the value of hx_service_trouble_info.trouble_code
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public String getTroubleCode() {
        return troubleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_trouble_info.trouble_code
     *
     * @param troubleCode the value for hx_service_trouble_info.trouble_code
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public void setTroubleCode(String troubleCode) {
        this.troubleCode = troubleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_trouble_info.repair_content
     *
     * @return the value of hx_service_trouble_info.repair_content
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public String getRepairContent() {
        return repairContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_trouble_info.repair_content
     *
     * @param repairContent the value for hx_service_trouble_info.repair_content
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public void setRepairContent(String repairContent) {
        this.repairContent = repairContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_trouble_info.trouble_reason
     *
     * @return the value of hx_service_trouble_info.trouble_reason
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public String getTroubleReason() {
        return troubleReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_trouble_info.trouble_reason
     *
     * @param troubleReason the value for hx_service_trouble_info.trouble_reason
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public void setTroubleReason(String troubleReason) {
        this.troubleReason = troubleReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_trouble_info.trouble_description
     *
     * @return the value of hx_service_trouble_info.trouble_description
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public String getTroubleDescription() {
        return troubleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_trouble_info.trouble_description
     *
     * @param troubleDescription the value for hx_service_trouble_info.trouble_description
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    public void setTroubleDescription(String troubleDescription) {
        this.troubleDescription = troubleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_service_trouble_info
     *
     * @mbggenerated Fri Aug 29 14:59:19 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", repairId=").append(repairId);
        sb.append(", troubleCode=").append(troubleCode);
        sb.append(", repairContent=").append(repairContent);
        sb.append(", troubleReason=").append(troubleReason);
        sb.append(", troubleDescription=").append(troubleDescription);
        sb.append("]");
        return sb.toString();
    }
}