package com.gome.gmhx.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.gome.gmhx.jbpm.JbpmWorkEntity;

public class HxServiceLongDistance implements JbpmWorkEntity{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.apply_id
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.apply_unit
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String applyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.sequence
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.mileage
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private Float mileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.other_fee
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private Float otherFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.customer_name
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.customer_phone
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String customerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.customer_address
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String customerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.machine_type
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String machineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.gome_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String gomeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.brand
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.machine_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String machineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.internal_machine_code1
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String internalMachineCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.internal_machine_code2
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String internalMachineCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.external_machine_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String externalMachineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.buy_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd")
    private Date buyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.install_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String installMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.install_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
	@DateTimeFormat(pattern="yyyy-MM-dd")
    private Date installDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.status
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.is_center_check_agree
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String isCenterCheckAgree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.center_check_comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String centerCheckComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.center_check_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String centerCheckMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.center_check_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date centerCheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.is_headquarters_check_agree
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String isHeadquartersCheckAgree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.headquarters_check_comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String headquartersCheckComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.headquarters_check_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String headquartersCheckMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.headquarters_check_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date headquartersCheckDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.create_man_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String createManS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.create_organization_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String createOrganizationS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.create_time_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date createTimeS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.alter_man_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String alterManS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.alter_organization_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String alterOrganizationS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.alter_time_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date alterTimeS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.process_intance_id
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String processInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.applicant
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    private String applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_long_distance.apply_time
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date applyDate;
    
    private String serviceUnit;
    
    private Integer isEffective;
    
    private String createPosition;

    public String getCreatePosition() {
		return createPosition;
	}

	public void setCreatePosition(String createPosition) {
		this.createPosition = createPosition;
	}

	public Integer getIsEffective() {
		return isEffective;
	}

	public void setIsEffective(Integer isEffective) {
		this.isEffective = isEffective;
	}

	public String getServiceUnit() {
		return serviceUnit;
	}

	public void setServiceUnit(String serviceUnit) {
		this.serviceUnit = serviceUnit;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.apply_id
     *
     * @return the value of hx_service_long_distance.apply_id
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.apply_id
     *
     * @param applyId the value for hx_service_long_distance.apply_id
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.apply_unit
     *
     * @return the value of hx_service_long_distance.apply_unit
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getApplyUnit() {
        return applyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.apply_unit
     *
     * @param applyUnit the value for hx_service_long_distance.apply_unit
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setApplyUnit(String applyUnit) {
        this.applyUnit = applyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.sequence
     *
     * @return the value of hx_service_long_distance.sequence
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.sequence
     *
     * @param sequence the value for hx_service_long_distance.sequence
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.mileage
     *
     * @return the value of hx_service_long_distance.mileage
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Float getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.mileage
     *
     * @param mileage the value for hx_service_long_distance.mileage
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setMileage(Float mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.other_fee
     *
     * @return the value of hx_service_long_distance.other_fee
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Float getOtherFee() {
        return otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.other_fee
     *
     * @param otherFee the value for hx_service_long_distance.other_fee
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setOtherFee(Float otherFee) {
        this.otherFee = otherFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.customer_name
     *
     * @return the value of hx_service_long_distance.customer_name
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.customer_name
     *
     * @param customerName the value for hx_service_long_distance.customer_name
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.customer_phone
     *
     * @return the value of hx_service_long_distance.customer_phone
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.customer_phone
     *
     * @param customerPhone the value for hx_service_long_distance.customer_phone
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.customer_address
     *
     * @return the value of hx_service_long_distance.customer_address
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.customer_address
     *
     * @param customerAddress the value for hx_service_long_distance.customer_address
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.machine_type
     *
     * @return the value of hx_service_long_distance.machine_type
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.machine_type
     *
     * @param machineType the value for hx_service_long_distance.machine_type
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.gome_code
     *
     * @return the value of hx_service_long_distance.gome_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getGomeCode() {
        return gomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.gome_code
     *
     * @param gomeCode the value for hx_service_long_distance.gome_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setGomeCode(String gomeCode) {
        this.gomeCode = gomeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.brand
     *
     * @return the value of hx_service_long_distance.brand
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.brand
     *
     * @param brand the value for hx_service_long_distance.brand
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.machine_code
     *
     * @return the value of hx_service_long_distance.machine_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getMachineCode() {
        return machineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.machine_code
     *
     * @param machineCode the value for hx_service_long_distance.machine_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setMachineCode(String machineCode) {
        this.machineCode = machineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.internal_machine_code1
     *
     * @return the value of hx_service_long_distance.internal_machine_code1
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getInternalMachineCode1() {
        return internalMachineCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.internal_machine_code1
     *
     * @param internalMachineCode1 the value for hx_service_long_distance.internal_machine_code1
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setInternalMachineCode1(String internalMachineCode1) {
        this.internalMachineCode1 = internalMachineCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.internal_machine_code2
     *
     * @return the value of hx_service_long_distance.internal_machine_code2
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getInternalMachineCode2() {
        return internalMachineCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.internal_machine_code2
     *
     * @param internalMachineCode2 the value for hx_service_long_distance.internal_machine_code2
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setInternalMachineCode2(String internalMachineCode2) {
        this.internalMachineCode2 = internalMachineCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.external_machine_code
     *
     * @return the value of hx_service_long_distance.external_machine_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getExternalMachineCode() {
        return externalMachineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.external_machine_code
     *
     * @param externalMachineCode the value for hx_service_long_distance.external_machine_code
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setExternalMachineCode(String externalMachineCode) {
        this.externalMachineCode = externalMachineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.buy_date
     *
     * @return the value of hx_service_long_distance.buy_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Date getBuyDate() {
        return buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.buy_date
     *
     * @param buyDate the value for hx_service_long_distance.buy_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setBuyDate(Date buyDate) {
        this.buyDate = buyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.install_man
     *
     * @return the value of hx_service_long_distance.install_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getInstallMan() {
        return installMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.install_man
     *
     * @param installMan the value for hx_service_long_distance.install_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setInstallMan(String installMan) {
        this.installMan = installMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.install_date
     *
     * @return the value of hx_service_long_distance.install_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Date getInstallDate() {
        return installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.install_date
     *
     * @param installDate the value for hx_service_long_distance.install_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setInstallDate(Date installDate) {
        this.installDate = installDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.status
     *
     * @return the value of hx_service_long_distance.status
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.status
     *
     * @param status the value for hx_service_long_distance.status
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.is_center_check_agree
     *
     * @return the value of hx_service_long_distance.is_center_check_agree
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getIsCenterCheckAgree() {
        return isCenterCheckAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.is_center_check_agree
     *
     * @param isCenterCheckAgree the value for hx_service_long_distance.is_center_check_agree
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setIsCenterCheckAgree(String isCenterCheckAgree) {
        this.isCenterCheckAgree = isCenterCheckAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.center_check_comment
     *
     * @return the value of hx_service_long_distance.center_check_comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getCenterCheckComment() {
        return centerCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.center_check_comment
     *
     * @param centerCheckComment the value for hx_service_long_distance.center_check_comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCenterCheckComment(String centerCheckComment) {
        this.centerCheckComment = centerCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.center_check_man
     *
     * @return the value of hx_service_long_distance.center_check_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getCenterCheckMan() {
        return centerCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.center_check_man
     *
     * @param centerCheckMan the value for hx_service_long_distance.center_check_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCenterCheckMan(String centerCheckMan) {
        this.centerCheckMan = centerCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.center_check_date
     *
     * @return the value of hx_service_long_distance.center_check_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Date getCenterCheckDate() {
        return centerCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.center_check_date
     *
     * @param centerCheckDate the value for hx_service_long_distance.center_check_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCenterCheckDate(Date centerCheckDate) {
        this.centerCheckDate = centerCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.is_headquarters_check_agree
     *
     * @return the value of hx_service_long_distance.is_headquarters_check_agree
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getIsHeadquartersCheckAgree() {
        return isHeadquartersCheckAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.is_headquarters_check_agree
     *
     * @param isHeadquartersCheckAgree the value for hx_service_long_distance.is_headquarters_check_agree
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setIsHeadquartersCheckAgree(String isHeadquartersCheckAgree) {
        this.isHeadquartersCheckAgree = isHeadquartersCheckAgree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.headquarters_check_comment
     *
     * @return the value of hx_service_long_distance.headquarters_check_comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getHeadquartersCheckComment() {
        return headquartersCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.headquarters_check_comment
     *
     * @param headquartersCheckComment the value for hx_service_long_distance.headquarters_check_comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setHeadquartersCheckComment(String headquartersCheckComment) {
        this.headquartersCheckComment = headquartersCheckComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.headquarters_check_man
     *
     * @return the value of hx_service_long_distance.headquarters_check_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getHeadquartersCheckMan() {
        return headquartersCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.headquarters_check_man
     *
     * @param headquartersCheckMan the value for hx_service_long_distance.headquarters_check_man
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setHeadquartersCheckMan(String headquartersCheckMan) {
        this.headquartersCheckMan = headquartersCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.headquarters_check_date
     *
     * @return the value of hx_service_long_distance.headquarters_check_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Date getHeadquartersCheckDate() {
        return headquartersCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.headquarters_check_date
     *
     * @param headquartersCheckDate the value for hx_service_long_distance.headquarters_check_date
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setHeadquartersCheckDate(Date headquartersCheckDate) {
        this.headquartersCheckDate = headquartersCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.comment
     *
     * @return the value of hx_service_long_distance.comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.comment
     *
     * @param comment the value for hx_service_long_distance.comment
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.create_man_s
     *
     * @return the value of hx_service_long_distance.create_man_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getCreateManS() {
        return createManS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.create_man_s
     *
     * @param createManS the value for hx_service_long_distance.create_man_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCreateManS(String createManS) {
        this.createManS = createManS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.create_organization_s
     *
     * @return the value of hx_service_long_distance.create_organization_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getCreateOrganizationS() {
        return createOrganizationS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.create_organization_s
     *
     * @param createOrganizationS the value for hx_service_long_distance.create_organization_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCreateOrganizationS(String createOrganizationS) {
        this.createOrganizationS = createOrganizationS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.create_time_s
     *
     * @return the value of hx_service_long_distance.create_time_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Date getCreateTimeS() {
        return createTimeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.create_time_s
     *
     * @param createTimeS the value for hx_service_long_distance.create_time_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setCreateTimeS(Date createTimeS) {
        this.createTimeS = createTimeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.alter_man_s
     *
     * @return the value of hx_service_long_distance.alter_man_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getAlterManS() {
        return alterManS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.alter_man_s
     *
     * @param alterManS the value for hx_service_long_distance.alter_man_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setAlterManS(String alterManS) {
        this.alterManS = alterManS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.alter_organization_s
     *
     * @return the value of hx_service_long_distance.alter_organization_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getAlterOrganizationS() {
        return alterOrganizationS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.alter_organization_s
     *
     * @param alterOrganizationS the value for hx_service_long_distance.alter_organization_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setAlterOrganizationS(String alterOrganizationS) {
        this.alterOrganizationS = alterOrganizationS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.alter_time_s
     *
     * @return the value of hx_service_long_distance.alter_time_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public Date getAlterTimeS() {
        return alterTimeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.alter_time_s
     *
     * @param alterTimeS the value for hx_service_long_distance.alter_time_s
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setAlterTimeS(Date alterTimeS) {
        this.alterTimeS = alterTimeS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.process_intance_id
     *
     * @return the value of hx_service_long_distance.process_intance_id
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getProcessInstanceId() {
        return processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.process_intance_id
     *
     * @param processIntanceId the value for hx_service_long_distance.process_intance_id
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_long_distance.applicant
     *
     * @return the value of hx_service_long_distance.applicant
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_long_distance.applicant
     *
     * @param applicant the value for hx_service_long_distance.applicant
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_service_long_distance
     *
     * @mbggenerated Wed Nov 05 15:17:54 CST 2014
     */

	@Override
	public String getWorkEntityId() {
		return applyId;
	}

	@Override
	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	@Override
	public Date getApplyDate() {
		return applyDate;
	}
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", applyId=").append(applyId);
        sb.append(", applyUnit=").append(applyUnit);
        sb.append(", sequence=").append(sequence);
        sb.append(", mileage=").append(mileage);
        sb.append(", otherFee=").append(otherFee);
        sb.append(", customerName=").append(customerName);
        sb.append(", customerPhone=").append(customerPhone);
        sb.append(", customerAddress=").append(customerAddress);
        sb.append(", machineType=").append(machineType);
        sb.append(", gomeCode=").append(gomeCode);
        sb.append(", brand=").append(brand);
        sb.append(", machineCode=").append(machineCode);
        sb.append(", internalMachineCode1=").append(internalMachineCode1);
        sb.append(", internalMachineCode2=").append(internalMachineCode2);
        sb.append(", externalMachineCode=").append(externalMachineCode);
        sb.append(", buyDate=").append(buyDate);
        sb.append(", installMan=").append(installMan);
        sb.append(", installDate=").append(installDate);
        sb.append(", status=").append(status);
        sb.append(", isCenterCheckAgree=").append(isCenterCheckAgree);
        sb.append(", centerCheckComment=").append(centerCheckComment);
        sb.append(", centerCheckMan=").append(centerCheckMan);
        sb.append(", centerCheckDate=").append(centerCheckDate);
        sb.append(", isHeadquartersCheckAgree=").append(isHeadquartersCheckAgree);
        sb.append(", headquartersCheckComment=").append(headquartersCheckComment);
        sb.append(", headquartersCheckMan=").append(headquartersCheckMan);
        sb.append(", headquartersCheckDate=").append(headquartersCheckDate);
        sb.append(", comment=").append(comment);
        sb.append(", createManS=").append(createManS);
        sb.append(", createOrganizationS=").append(createOrganizationS);
        sb.append(", createTimeS=").append(createTimeS);
        sb.append(", alterManS=").append(alterManS);
        sb.append(", alterOrganizationS=").append(alterOrganizationS);
        sb.append(", alterTimeS=").append(alterTimeS);
        sb.append(", processInstanceId=").append(processInstanceId);
        sb.append(", applicant=").append(applicant);
        sb.append(", applyTime=").append(applyDate);
        sb.append("]");
        return sb.toString();
    }

}