package com.gome.gmhx.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class HxServiceCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.customer_id
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.customer_name
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.customer_type
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String customerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.customer_sex
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String customerSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.member_num
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String memberNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.province
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.area_code
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.phone
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.telephone
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.e_mail
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.postcode
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.address
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.note
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.create_man_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String createManC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.create_organization_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String createOrganizationC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.create_time_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date createTimeC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.alter_man_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String alterManC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.alter_organization_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    private String alterOrganizationC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_service_customer.alter_time_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date alterTimeC;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.customer_id
     *
     * @return the value of hx_service_customer.customer_id
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.customer_id
     *
     * @param customerId the value for hx_service_customer.customer_id
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.customer_name
     *
     * @return the value of hx_service_customer.customer_name
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.customer_name
     *
     * @param customerName the value for hx_service_customer.customer_name
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.customer_type
     *
     * @return the value of hx_service_customer.customer_type
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.customer_type
     *
     * @param customerType the value for hx_service_customer.customer_type
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.customer_sex
     *
     * @return the value of hx_service_customer.customer_sex
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getCustomerSex() {
        return customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.customer_sex
     *
     * @param customerSex the value for hx_service_customer.customer_sex
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setCustomerSex(String customerSex) {
        this.customerSex = customerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.member_num
     *
     * @return the value of hx_service_customer.member_num
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getMemberNum() {
        return memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.member_num
     *
     * @param memberNum the value for hx_service_customer.member_num
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setMemberNum(String memberNum) {
        this.memberNum = memberNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.province
     *
     * @return the value of hx_service_customer.province
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.province
     *
     * @param province the value for hx_service_customer.province
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.area_code
     *
     * @return the value of hx_service_customer.area_code
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.area_code
     *
     * @param areaCode the value for hx_service_customer.area_code
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.phone
     *
     * @return the value of hx_service_customer.phone
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.phone
     *
     * @param phone the value for hx_service_customer.phone
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.telephone
     *
     * @return the value of hx_service_customer.telephone
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.telephone
     *
     * @param telephone the value for hx_service_customer.telephone
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.postcode
     *
     * @return the value of hx_service_customer.postcode
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.postcode
     *
     * @param postcode the value for hx_service_customer.postcode
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.address
     *
     * @return the value of hx_service_customer.address
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.address
     *
     * @param address the value for hx_service_customer.address
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.note
     *
     * @return the value of hx_service_customer.note
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.note
     *
     * @param note the value for hx_service_customer.note
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.create_man_c
     *
     * @return the value of hx_service_customer.create_man_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getCreateManC() {
        return createManC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.create_man_c
     *
     * @param createManC the value for hx_service_customer.create_man_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setCreateManC(String createManC) {
        this.createManC = createManC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.create_organization_c
     *
     * @return the value of hx_service_customer.create_organization_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getCreateOrganizationC() {
        return createOrganizationC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.create_organization_c
     *
     * @param createOrganizationC the value for hx_service_customer.create_organization_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setCreateOrganizationC(String createOrganizationC) {
        this.createOrganizationC = createOrganizationC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.create_time_c
     *
     * @return the value of hx_service_customer.create_time_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public Date getCreateTimeC() {
        return createTimeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.create_time_c
     *
     * @param createTimeC the value for hx_service_customer.create_time_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setCreateTimeC(Date createTimeC) {
        this.createTimeC = createTimeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.alter_man_c
     *
     * @return the value of hx_service_customer.alter_man_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getAlterManC() {
        return alterManC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.alter_man_c
     *
     * @param alterManC the value for hx_service_customer.alter_man_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setAlterManC(String alterManC) {
        this.alterManC = alterManC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.alter_organization_c
     *
     * @return the value of hx_service_customer.alter_organization_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public String getAlterOrganizationC() {
        return alterOrganizationC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.alter_organization_c
     *
     * @param alterOrganizationC the value for hx_service_customer.alter_organization_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setAlterOrganizationC(String alterOrganizationC) {
        this.alterOrganizationC = alterOrganizationC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_service_customer.alter_time_c
     *
     * @return the value of hx_service_customer.alter_time_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public Date getAlterTimeC() {
        return alterTimeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_service_customer.alter_time_c
     *
     * @param alterTimeC the value for hx_service_customer.alter_time_c
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    public void setAlterTimeC(Date alterTimeC) {
        this.alterTimeC = alterTimeC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hx_service_customer
     *
     * @mbggenerated Mon Sep 15 09:43:28 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerId=").append(customerId);
        sb.append(", customerName=").append(customerName);
        sb.append(", customerType=").append(customerType);
        sb.append(", customerSex=").append(customerSex);
        sb.append(", memberNum=").append(memberNum);
        sb.append(", province=").append(province);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", phone=").append(phone);
        sb.append(", telephone=").append(telephone);
        sb.append(", email=").append(email);
        sb.append(", postcode=").append(postcode);
        sb.append(", address=").append(address);
        sb.append(", note=").append(note);
        sb.append(", createManC=").append(createManC);
        sb.append(", createOrganizationC=").append(createOrganizationC);
        sb.append(", createTimeC=").append(createTimeC);
        sb.append(", alterManC=").append(alterManC);
        sb.append(", alterOrganizationC=").append(alterOrganizationC);
        sb.append(", alterTimeC=").append(alterTimeC);
        sb.append("]");
        return sb.toString();
    }

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}