package com.gome.gmhx.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class JlAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.CZY01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private String czy01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.RYXX01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private String ryxx01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.RYXM
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private String ryxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.CZYMM
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private String czymm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.GSXX01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private String gsxx01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.BM01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private String bm01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.AZWD01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private String azwd01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.WDMC
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private String wdmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.QSRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private Date qsrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.ZZRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private Date zzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.ZT
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private BigDecimal zt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.CCRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private Date ccrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_account.ZXBJ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    private BigDecimal zxbj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.CZY01
     *
     * @return the value of jl_account.CZY01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public String getCzy01() {
        return czy01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.CZY01
     *
     * @param czy01 the value for jl_account.CZY01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setCzy01(String czy01) {
        this.czy01 = czy01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.RYXX01
     *
     * @return the value of jl_account.RYXX01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public String getRyxx01() {
        return ryxx01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.RYXX01
     *
     * @param ryxx01 the value for jl_account.RYXX01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setRyxx01(String ryxx01) {
        this.ryxx01 = ryxx01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.RYXM
     *
     * @return the value of jl_account.RYXM
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public String getRyxm() {
        return ryxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.RYXM
     *
     * @param ryxm the value for jl_account.RYXM
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setRyxm(String ryxm) {
        this.ryxm = ryxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.CZYMM
     *
     * @return the value of jl_account.CZYMM
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public String getCzymm() {
        return czymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.CZYMM
     *
     * @param czymm the value for jl_account.CZYMM
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setCzymm(String czymm) {
        this.czymm = czymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.GSXX01
     *
     * @return the value of jl_account.GSXX01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public String getGsxx01() {
        return gsxx01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.GSXX01
     *
     * @param gsxx01 the value for jl_account.GSXX01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setGsxx01(String gsxx01) {
        this.gsxx01 = gsxx01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.BM01
     *
     * @return the value of jl_account.BM01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public String getBm01() {
        return bm01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.BM01
     *
     * @param bm01 the value for jl_account.BM01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setBm01(String bm01) {
        this.bm01 = bm01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.AZWD01
     *
     * @return the value of jl_account.AZWD01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public String getAzwd01() {
        return azwd01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.AZWD01
     *
     * @param azwd01 the value for jl_account.AZWD01
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setAzwd01(String azwd01) {
        this.azwd01 = azwd01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.WDMC
     *
     * @return the value of jl_account.WDMC
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public String getWdmc() {
        return wdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.WDMC
     *
     * @param wdmc the value for jl_account.WDMC
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setWdmc(String wdmc) {
        this.wdmc = wdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.QSRQ
     *
     * @return the value of jl_account.QSRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public Date getQsrq() {
        return qsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.QSRQ
     *
     * @param qsrq the value for jl_account.QSRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setQsrq(Date qsrq) {
        this.qsrq = qsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.ZZRQ
     *
     * @return the value of jl_account.ZZRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public Date getZzrq() {
        return zzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.ZZRQ
     *
     * @param zzrq the value for jl_account.ZZRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setZzrq(Date zzrq) {
        this.zzrq = zzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.ZT
     *
     * @return the value of jl_account.ZT
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public BigDecimal getZt() {
        return zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.ZT
     *
     * @param zt the value for jl_account.ZT
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setZt(BigDecimal zt) {
        this.zt = zt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.CCRQ
     *
     * @return the value of jl_account.CCRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public Date getCcrq() {
        return ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.CCRQ
     *
     * @param ccrq the value for jl_account.CCRQ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setCcrq(Date ccrq) {
        this.ccrq = ccrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_account.ZXBJ
     *
     * @return the value of jl_account.ZXBJ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public BigDecimal getZxbj() {
        return zxbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_account.ZXBJ
     *
     * @param zxbj the value for jl_account.ZXBJ
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    public void setZxbj(BigDecimal zxbj) {
        this.zxbj = zxbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_account
     *
     * @mbggenerated Tue Jul 29 10:38:17 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", czy01=").append(czy01);
        sb.append(", ryxx01=").append(ryxx01);
        sb.append(", ryxm=").append(ryxm);
        sb.append(", czymm=").append(czymm);
        sb.append(", gsxx01=").append(gsxx01);
        sb.append(", bm01=").append(bm01);
        sb.append(", azwd01=").append(azwd01);
        sb.append(", wdmc=").append(wdmc);
        sb.append(", qsrq=").append(qsrq);
        sb.append(", zzrq=").append(zzrq);
        sb.append(", zt=").append(zt);
        sb.append(", ccrq=").append(ccrq);
        sb.append(", zxbj=").append(zxbj);
        sb.append("]");
        return sb.toString();
    }
}