package com.gome.gmhx.entity;

import com.gome.common.util.FDate;
import java.util.Date;

public class EmpAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.EmpNo
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String empno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.EmpName
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String empname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.AD_Account
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String adAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.AD_AccountPwd
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String adAccountpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.AP_Account
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String apAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.AP_AccountPwd
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String apAccountpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.CompCode
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String compcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.CompName
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String compname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.Phone
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.Email
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.State
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.NeedModify
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String needmodify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.OperatorType
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String operatortype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.CreateDate
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.CreateTime
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.ModifyDate
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_Account.ModifyTime
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.EmpNo
     *
     * @return the value of t_Account.EmpNo
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.EmpNo
     *
     * @param empno the value for t_Account.EmpNo
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setEmpno(String empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.EmpName
     *
     * @return the value of t_Account.EmpName
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.EmpName
     *
     * @param empname the value for t_Account.EmpName
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setEmpname(String empname) {
        this.empname = empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.AD_Account
     *
     * @return the value of t_Account.AD_Account
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getAdAccount() {
        return adAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.AD_Account
     *
     * @param adAccount the value for t_Account.AD_Account
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setAdAccount(String adAccount) {
        this.adAccount = adAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.AD_AccountPwd
     *
     * @return the value of t_Account.AD_AccountPwd
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getAdAccountpwd() {
        return adAccountpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.AD_AccountPwd
     *
     * @param adAccountpwd the value for t_Account.AD_AccountPwd
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setAdAccountpwd(String adAccountpwd) {
        this.adAccountpwd = adAccountpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.AP_Account
     *
     * @return the value of t_Account.AP_Account
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getApAccount() {
        return apAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.AP_Account
     *
     * @param apAccount the value for t_Account.AP_Account
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setApAccount(String apAccount) {
        this.apAccount = apAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.AP_AccountPwd
     *
     * @return the value of t_Account.AP_AccountPwd
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getApAccountpwd() {
        return apAccountpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.AP_AccountPwd
     *
     * @param apAccountpwd the value for t_Account.AP_AccountPwd
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setApAccountpwd(String apAccountpwd) {
        this.apAccountpwd = apAccountpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.CompCode
     *
     * @return the value of t_Account.CompCode
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getCompcode() {
        return compcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.CompCode
     *
     * @param compcode the value for t_Account.CompCode
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setCompcode(String compcode) {
        this.compcode = compcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.CompName
     *
     * @return the value of t_Account.CompName
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getCompname() {
        return compname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.CompName
     *
     * @param compname the value for t_Account.CompName
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setCompname(String compname) {
        this.compname = compname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.Phone
     *
     * @return the value of t_Account.Phone
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.Phone
     *
     * @param phone the value for t_Account.Phone
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.Email
     *
     * @return the value of t_Account.Email
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.Email
     *
     * @param email the value for t_Account.Email
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.State
     *
     * @return the value of t_Account.State
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.State
     *
     * @param state the value for t_Account.State
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.NeedModify
     *
     * @return the value of t_Account.NeedModify
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getNeedmodify() {
        return needmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.NeedModify
     *
     * @param needmodify the value for t_Account.NeedModify
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setNeedmodify(String needmodify) {
        this.needmodify = needmodify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.OperatorType
     *
     * @return the value of t_Account.OperatorType
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getOperatortype() {
        return operatortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.OperatorType
     *
     * @param operatortype the value for t_Account.OperatorType
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setOperatortype(String operatortype) {
        this.operatortype = operatortype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.CreateDate
     *
     * @return the value of t_Account.CreateDate
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.CreateDate
     *
     * @param createdate the value for t_Account.CreateDate
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setCreatedate(String createdate) {
        this.createdate = FDate.getDate(createdate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.CreateDate
     *
     * @param createdate the value for t_Account.CreateDate
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.CreateTime
     *
     * @return the value of t_Account.CreateTime
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.CreateTime
     *
     * @param createtime the value for t_Account.CreateTime
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.ModifyDate
     *
     * @return the value of t_Account.ModifyDate
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.ModifyDate
     *
     * @param modifydate the value for t_Account.ModifyDate
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setModifydate(String modifydate) {
        this.modifydate = FDate.getDate(modifydate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.ModifyDate
     *
     * @param modifydate the value for t_Account.ModifyDate
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_Account.ModifyTime
     *
     * @return the value of t_Account.ModifyTime
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_Account.ModifyTime
     *
     * @param modifytime the value for t_Account.ModifyTime
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_Account
     *
     * @mbggenerated Thu Feb 27 10:14:03 CST 2014
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", empno=").append(empno);
        sb.append(", empname=").append(empname);
        sb.append(", adAccount=").append(adAccount);
        sb.append(", adAccountpwd=").append(adAccountpwd);
        sb.append(", apAccount=").append(apAccount);
        sb.append(", apAccountpwd=").append(apAccountpwd);
        sb.append(", compcode=").append(compcode);
        sb.append(", compname=").append(compname);
        sb.append(", phone=").append(phone);
        sb.append(", email=").append(email);
        sb.append(", state=").append(state);
        sb.append(", needmodify=").append(needmodify);
        sb.append(", operatortype=").append(operatortype);
        sb.append(", createdate=").append(createdate);
        sb.append(", createtime=").append(createtime);
        sb.append(", modifydate=").append(modifydate);
        sb.append(", modifytime=").append(modifytime);
        sb.append("]");
        return sb.toString();
    }
}