package com.gome.gmhx.entity.vo;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.gome.gmhx.entity.HxGoodbillKey;

public class HxGoodbillVO extends HxGoodbillKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.GSMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String gsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.KHMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String khmc;

    private String xslx;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.FPH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String fph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.JZRQ
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private Date jzrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.YYYDM
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String yyydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.YYYMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String yyymc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.XSJE
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private BigDecimal xsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.SPBM
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String spbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.SPMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String spmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.DZBM01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String dzbm01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.BMMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String bmmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.SPFL01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String spfl01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.SPFLMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String spflmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.PPB01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String ppb01;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.PPBMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private String ppbmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.ZPBJ
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private Integer zpbj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.ZP_THDH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private Long zpThdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hx_goodbill.SHULIANG
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    private Long shuliang;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date startDate;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date endDate;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.GSMC
     *
     * @return the value of hx_goodbill.GSMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getGsmc() {
        return gsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.GSMC
     *
     * @param gsmc the value for hx_goodbill.GSMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setGsmc(String gsmc) {
        this.gsmc = gsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.KHMC
     *
     * @return the value of hx_goodbill.KHMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getKhmc() {
        return khmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.KHMC
     *
     * @param khmc the value for hx_goodbill.KHMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setKhmc(String khmc) {
        this.khmc = khmc;
    }

    public String getXslx() {
		return xslx;
	}

	public void setXslx(String xslx) {
		this.xslx = xslx;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.FPH
     *
     * @return the value of hx_goodbill.FPH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getFph() {
        return fph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.FPH
     *
     * @param fph the value for hx_goodbill.FPH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setFph(String fph) {
        this.fph = fph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.JZRQ
     *
     * @return the value of hx_goodbill.JZRQ
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public Date getJzrq() {
        return jzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.JZRQ
     *
     * @param jzrq the value for hx_goodbill.JZRQ
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setJzrq(Date jzrq) {
        this.jzrq = jzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.YYYDM
     *
     * @return the value of hx_goodbill.YYYDM
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getYyydm() {
        return yyydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.YYYDM
     *
     * @param yyydm the value for hx_goodbill.YYYDM
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setYyydm(String yyydm) {
        this.yyydm = yyydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.YYYMC
     *
     * @return the value of hx_goodbill.YYYMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getYyymc() {
        return yyymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.YYYMC
     *
     * @param yyymc the value for hx_goodbill.YYYMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setYyymc(String yyymc) {
        this.yyymc = yyymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.XSJE
     *
     * @return the value of hx_goodbill.XSJE
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public BigDecimal getXsje() {
        return xsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.XSJE
     *
     * @param xsje the value for hx_goodbill.XSJE
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setXsje(BigDecimal xsje) {
        this.xsje = xsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.SPBM
     *
     * @return the value of hx_goodbill.SPBM
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getSpbm() {
        return spbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.SPBM
     *
     * @param spbm the value for hx_goodbill.SPBM
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setSpbm(String spbm) {
        this.spbm = spbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.SPMC
     *
     * @return the value of hx_goodbill.SPMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getSpmc() {
        return spmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.SPMC
     *
     * @param spmc the value for hx_goodbill.SPMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setSpmc(String spmc) {
        this.spmc = spmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.DZBM01
     *
     * @return the value of hx_goodbill.DZBM01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getDzbm01() {
        return dzbm01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.DZBM01
     *
     * @param dzbm01 the value for hx_goodbill.DZBM01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setDzbm01(String dzbm01) {
        this.dzbm01 = dzbm01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.BMMC
     *
     * @return the value of hx_goodbill.BMMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getBmmc() {
        return bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.BMMC
     *
     * @param bmmc the value for hx_goodbill.BMMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setBmmc(String bmmc) {
        this.bmmc = bmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.SPFL01
     *
     * @return the value of hx_goodbill.SPFL01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getSpfl01() {
        return spfl01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.SPFL01
     *
     * @param spfl01 the value for hx_goodbill.SPFL01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setSpfl01(String spfl01) {
        this.spfl01 = spfl01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.SPFLMC
     *
     * @return the value of hx_goodbill.SPFLMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getSpflmc() {
        return spflmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.SPFLMC
     *
     * @param spflmc the value for hx_goodbill.SPFLMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setSpflmc(String spflmc) {
        this.spflmc = spflmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.PPB01
     *
     * @return the value of hx_goodbill.PPB01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getPpb01() {
        return ppb01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.PPB01
     *
     * @param ppb01 the value for hx_goodbill.PPB01
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setPpb01(String ppb01) {
        this.ppb01 = ppb01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.PPBMC
     *
     * @return the value of hx_goodbill.PPBMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public String getPpbmc() {
        return ppbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.PPBMC
     *
     * @param ppbmc the value for hx_goodbill.PPBMC
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setPpbmc(String ppbmc) {
        this.ppbmc = ppbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.ZPBJ
     *
     * @return the value of hx_goodbill.ZPBJ
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public Integer getZpbj() {
        return zpbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.ZPBJ
     *
     * @param zpbj the value for hx_goodbill.ZPBJ
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setZpbj(Integer zpbj) {
        this.zpbj = zpbj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.ZP_THDH
     *
     * @return the value of hx_goodbill.ZP_THDH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public Long getZpThdh() {
        return zpThdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.ZP_THDH
     *
     * @param zpThdh the value for hx_goodbill.ZP_THDH
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setZpThdh(Long zpThdh) {
        this.zpThdh = zpThdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hx_goodbill.SHULIANG
     *
     * @return the value of hx_goodbill.SHULIANG
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public Long getShuliang() {
        return shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hx_goodbill.SHULIANG
     *
     * @param shuliang the value for hx_goodbill.SHULIANG
     *
     * @mbggenerated Wed Aug 27 18:18:34 CST 2014
     */
    public void setShuliang(Long shuliang) {
        this.shuliang = shuliang;
    }

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
}